/**
 * The fifteen buildings of the Over City, as data.
 *
 * ## What is frozen and why
 *
 * `tilesWide`/`tilesHigh` are the *derived* footprints of the art each building
 * replaces — `ceil(frameWidth / tileScale)` — and the town plan hard-codes plot
 * positions against them without ever restating them. One tile either way and a
 * plot overlaps its neighbour several layers away from this file.
 * `scripts/buildinggen/fixtures/footprints.json` is the recorded baseline and
 * the generator diffs against it.
 *
 * `door.col` and `door.gapTiles` come from the same fixture, so every building's
 * entrance stays in the frontage the streets were painted around. The *painted*
 * door may be wider than that gap; the tiles beside it are blocked whatever the
 * art does.
 *
 * `seed` is fixed per building. Two bakes of an unchanged spec are byte-equal,
 * which is what makes a diff on this directory mean "the art changed".
 *
 * ## Why the numbers vary as much as they do
 *
 * `life.frames` is deliberately different building to building. Every animated
 * building in town shares one 8 fps clock, so equal frame counts would put the
 * whole street on the same beat and the town would pulse. Six, seven, eight and
 * nine frames drift against each other for a long time before they realign.
 */

import type { BuildingSpec } from './spec.js';

/**
 * Seeds are spread far apart rather than sequential: adjacent seeds produce
 * visibly related noise at low octaves, and two cottages side by side on
 * Garrison Row would have shown the same tonal blocking on their walls.
 */
const SEED_BLACKWOOD = 730101;
const SEED_SHEPHERD = 730211;
const SEED_BARRACKS = 730337;
const SEED_CARTWRIGHT = 730459;
const SEED_TEMPLE = 730571;
const SEED_HERB = 730693;
const SEED_STORE = 730817;
const SEED_INN = 730939;
const SEED_FLAGON = 731063;
const SEED_HILDA = 731179;
const SEED_SMITHY = 731291;
const SEED_STUMP = 731417;
const SEED_SIGNET = 731533;
const SEED_DESPERADO = 731659;
const SEED_MILL = 731777;

/**
 * The Sleeping Cat Inn — the flagship, and the pilot the rest were measured
 * against. Two stories of timber frame over a stone plinth, the upper jettied
 * out over the street, golden thatch, and a cat asleep on the upstairs sill.
 */
const SLEEPING_CAT_INN: BuildingSpec = {
  key: 'sleeping_cat_inn',
  file: 'sleeping_cat_inn.png',
  title: 'The Sleeping Cat Inn',
  replaces: 'small_inn',
  tilesWide: 8,
  tilesHigh: 6,
  seed: SEED_INN,
  stories: 2,
  sideReturnTiles: 0.55,
  facade: {
    ground: {
      material: 'fieldstone',
      ramp: 'fieldstone',
      trimRamp: 'mortar',
      grime: 0.22,
      moss: 0.18,
    },
    upper: {
      material: 'timber_frame',
      ramp: 'oak_beam',
      trimRamp: 'plaster_cream',
      grime: 0.16,
      moss: 0,
    },
    groundStoryTiles: 1.5,
    foundationTiles: 0.4,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 1.42,
        heightTiles: 0.16,
        ramp: 'oak_beam',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'thatch',
    ramp: 'thatch_gold',
    ridgeRamp: 'ridge_thatch',
    depthTiles: 1.9,
    overhangTiles: 0.3,
    ridgeSagTiles: 0.06,
    mossy: false,
    disrepair: 0.12,
    chimneys: [{ col: 1.4, widthTiles: 0.5, heightTiles: 0.7, ramp: 'fieldstone', smokes: true }],
    dormers: [],
  },
  door: {
    col: 2,
    gapTiles: 2,
    paintedWidthTiles: 1.5,
    style: 'arched',
    arch: 'round',
    ramp: 'oak_beam',
    hardware: true,
    stepTiles: 0.16,
  },
  windows: [
    {
      col: 0.6,
      baseAboveGroundTiles: 0.55,
      widthTiles: 0.85,
      heightTiles: 0.75,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: true,
    },
    {
      col: 5.1,
      baseAboveGroundTiles: 0.55,
      widthTiles: 0.85,
      heightTiles: 0.75,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: true,
    },
    {
      col: 1.1,
      baseAboveGroundTiles: 1.85,
      widthTiles: 0.8,
      heightTiles: 0.7,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: false,
    },
    {
      col: 4.6,
      baseAboveGroundTiles: 1.85,
      widthTiles: 0.9,
      heightTiles: 0.7,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'letter_board',
      col: 2.6,
      baseAboveGroundTiles: 2.42,
      widthTiles: 1.85,
      heightTiles: 0.4,
      ramp: 'oak_beam',
      accentRamp: 'plaster_cream',
      label: 'INN',
    },
    {
      kind: 'barrel',
      col: 6.0,
      baseAboveGroundTiles: 0,
      widthTiles: 0.5,
      heightTiles: 0.6,
      ramp: 'oak_beam',
      accentRamp: 'iron_black',
    },
    {
      kind: 'crate',
      col: 0.2,
      baseAboveGroundTiles: 0,
      widthTiles: 0.55,
      heightTiles: 0.45,
      ramp: 'sawn_pine',
      accentRamp: 'iron_black',
    },
  ],
  life: {
    frames: 8,
    effects: [
      {
        kind: 'sleeping_cat',
        col: 4.7,
        baseAboveGroundTiles: 1.85,
        widthTiles: 0.8,
        heightTiles: 0.42,
        ramp: 'oak_beam',
        cycles: 1,
        phase: 0,
      },
      {
        kind: 'window_breathe',
        col: 0.6,
        baseAboveGroundTiles: 0.55,
        widthTiles: 0.85,
        heightTiles: 0.75,
        ramp: 'hearth_glow',
        cycles: 1,
        phase: 0.35,
      },
      {
        kind: 'chimney_smoke',
        col: 1.4,
        baseAboveGroundTiles: 5.0,
        widthTiles: 0.5,
        heightTiles: 1.5,
        ramp: 'smoke',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** Blackwood Lodge — the cult hideout at the end of a dead-end alley. */
const BLACKWOOD_LODGE: BuildingSpec = {
  key: 'blackwood_lodge',
  file: 'blackwood_lodge.png',
  title: 'Blackwood Lodge',
  replaces: 'village_house_2',
  tilesWide: 7,
  tilesHigh: 6,
  seed: SEED_BLACKWOOD,
  stories: 1,
  sideReturnTiles: 0.5,
  facade: {
    ground: {
      material: 'plank',
      ramp: 'stained_timber',
      trimRamp: 'dark_mortar',
      grime: 0.34,
      moss: 0.26,
    },
    groundStoryTiles: 2.2,
    foundationTiles: 0.35,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.34,
        heightTiles: 0.12,
        ramp: 'stained_timber',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'shake',
    ramp: 'shake_brown',
    ridgeRamp: 'ridge_dark',
    depthTiles: 2.2,
    overhangTiles: 0.34,
    ridgeSagTiles: 0,
    mossy: true,
    disrepair: 0.2,
    chimneys: [
      { col: 5.0, widthTiles: 0.45, heightTiles: 0.6, ramp: 'dark_dressed_stone', smokes: false },
    ],
    dormers: [],
  },
  door: {
    col: 3,
    gapTiles: 1,
    paintedWidthTiles: 1.1,
    style: 'plank',
    arch: 'flat_lintel',
    ramp: 'stained_timber',
    hardware: true,
    stepTiles: 0.12,
  },
  windows: [
    {
      col: 1.0,
      baseAboveGroundTiles: 1.15,
      widthTiles: 0.5,
      heightTiles: 0.85,
      style: 'shuttered',
      lit: true,
      glowRamp: 'moon_glow',
      shutters: true,
      shutterRamp: 'stained_timber',
      flowerBox: false,
    },
    {
      col: 5.2,
      baseAboveGroundTiles: 1.15,
      widthTiles: 0.5,
      heightTiles: 0.85,
      style: 'shuttered',
      lit: false,
      shutters: true,
      shutterRamp: 'stained_timber',
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'charm_string',
      col: 2.3,
      baseAboveGroundTiles: 1.6,
      widthTiles: 0.7,
      heightTiles: 0.8,
      ramp: 'iron_black',
      accentRamp: 'moon_glow',
    },
    {
      kind: 'vine',
      col: 0.45,
      baseAboveGroundTiles: 0,
      widthTiles: 0.6,
      heightTiles: 2.4,
      ramp: 'leaf_green',
      accentRamp: 'stained_timber',
    },
  ],
  life: {
    frames: 9,
    effects: [
      {
        kind: 'window_breathe',
        col: 1.0,
        baseAboveGroundTiles: 1.15,
        widthTiles: 0.5,
        heightTiles: 0.85,
        ramp: 'moon_glow',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** Shepherd's Cabin — the humblest thing on Garrison Row. */
const SHEPHERDS_CABIN: BuildingSpec = {
  key: 'shepherds_cabin',
  file: 'shepherds_cabin.png',
  title: "Shepherd's Cabin",
  replaces: 'village_house_1',
  tilesWide: 7,
  tilesHigh: 6,
  seed: SEED_SHEPHERD,
  stories: 1,
  sideReturnTiles: 0.5,
  facade: {
    ground: {
      material: 'plaster',
      ramp: 'plaster_cream',
      trimRamp: 'fieldstone',
      grime: 0.24,
      moss: 0.22,
    },
    groundStoryTiles: 2.0,
    foundationTiles: 0.55,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.55,
        heightTiles: 0.14,
        ramp: 'fieldstone',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'thatch',
    ramp: 'thatch_gold',
    ridgeRamp: 'ridge_thatch',
    depthTiles: 2.1,
    overhangTiles: 0.32,
    ridgeSagTiles: 0.1,
    mossy: true,
    disrepair: 0.24,
    chimneys: [{ col: 4.6, widthTiles: 0.45, heightTiles: 0.62, ramp: 'fieldstone', smokes: true }],
    dormers: [],
  },
  door: {
    col: 3,
    gapTiles: 1,
    paintedWidthTiles: 1.05,
    style: 'plank',
    arch: 'flat_lintel',
    ramp: 'weathered_plank',
    hardware: true,
    stepTiles: 0.14,
  },
  windows: [
    {
      col: 1.1,
      baseAboveGroundTiles: 1.25,
      widthTiles: 0.75,
      heightTiles: 0.62,
      style: 'shuttered',
      lit: true,
      shutters: true,
      shutterRamp: 'shutter_green',
      flowerBox: false,
    },
    {
      col: 4.9,
      baseAboveGroundTiles: 1.25,
      widthTiles: 0.75,
      heightTiles: 0.62,
      style: 'shuttered',
      lit: false,
      shutters: true,
      shutterRamp: 'shutter_green',
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'firewood',
      col: 5.4,
      baseAboveGroundTiles: 0,
      widthTiles: 1.1,
      heightTiles: 0.8,
      ramp: 'oak_beam',
      accentRamp: 'weathered_plank',
    },
    {
      kind: 'wool_bale',
      col: 0.3,
      baseAboveGroundTiles: 0,
      widthTiles: 0.9,
      heightTiles: 0.7,
      ramp: 'plaster_cream',
      accentRamp: 'weathered_plank',
    },
    {
      kind: 'crook',
      col: 2.3,
      baseAboveGroundTiles: 0,
      widthTiles: 0.3,
      heightTiles: 1.6,
      ramp: 'weathered_plank',
      accentRamp: 'iron_black',
    },
  ],
  life: {
    frames: 7,
    effects: [
      {
        kind: 'chimney_smoke',
        col: 4.6,
        baseAboveGroundTiles: 5.0,
        widthTiles: 0.45,
        heightTiles: 1.5,
        ramp: 'smoke',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/**
 * The Barracks — a stone garrison, and the town's safe room.
 *
 * The blue slate roof is kept because it is how returning players find the
 * building from across Garrison Row. The sanctuary cues layered over it — lit
 * lanterns flanking the door, an open-shuttered warm window, a welcome brazier —
 * are the only reason the art differs from a guardhouse: the safe room lives
 * here, and a player looking for it should be able to tell from the street.
 */
const BARRACKS: BuildingSpec = {
  key: 'barracks',
  file: 'barracks.png',
  title: 'The Barracks',
  replaces: 'barracks',
  tilesWide: 8,
  tilesHigh: 6,
  seed: SEED_BARRACKS,
  stories: 1,
  sideReturnTiles: 0.6,
  facade: {
    ground: {
      material: 'coursed_stone',
      ramp: 'garrison_stone',
      trimRamp: 'mortar',
      grime: 0.2,
      moss: 0.1,
    },
    groundStoryTiles: 2.6,
    foundationTiles: 0.5,
    quoins: true,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.5,
        heightTiles: 0.16,
        ramp: 'garrison_stone',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 1.95,
        heightTiles: 0.22,
        ramp: 'garrison_stone',
        projecting: true,
      },
    ],
    pilasters: 5,
    pilasterRamp: 'garrison_stone',
  },
  roof: {
    material: 'slate',
    ramp: 'slate_blue',
    ridgeRamp: 'ridge_dark',
    depthTiles: 1.7,
    overhangTiles: 0.26,
    ridgeSagTiles: 0,
    mossy: false,
    disrepair: 0.05,
    chimneys: [
      { col: 6.2, widthTiles: 0.5, heightTiles: 0.65, ramp: 'garrison_stone', smokes: true },
    ],
    dormers: [],
  },
  door: {
    col: 3,
    gapTiles: 2,
    paintedWidthTiles: 1.7,
    style: 'double',
    arch: 'round',
    ramp: 'oak_beam',
    hardware: true,
    stepTiles: 0.2,
  },
  windows: [
    {
      col: 1.0,
      baseAboveGroundTiles: 1.15,
      widthTiles: 0.55,
      heightTiles: 0.9,
      style: 'arched',
      lit: false,
      shutters: false,
      flowerBox: false,
    },
    {
      col: 6.0,
      baseAboveGroundTiles: 1.35,
      widthTiles: 0.85,
      heightTiles: 0.7,
      style: 'shuttered',
      lit: true,
      shutters: true,
      shutterRamp: 'shutter_red',
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'relief_board',
      device: 'crossed_weapons',
      col: 3.1,
      baseAboveGroundTiles: 2.05,
      widthTiles: 1.5,
      heightTiles: 0.85,
      ramp: 'garrison_stone',
      accentRamp: 'iron_black',
    },
    {
      kind: 'lantern',
      col: 2.4,
      baseAboveGroundTiles: 1.5,
      widthTiles: 0.35,
      heightTiles: 0.5,
      ramp: 'hearth_glow',
      accentRamp: 'iron_black',
    },
    {
      kind: 'lantern',
      col: 4.9,
      baseAboveGroundTiles: 1.5,
      widthTiles: 0.35,
      heightTiles: 0.5,
      ramp: 'hearth_glow',
      accentRamp: 'iron_black',
    },
    {
      kind: 'brazier',
      col: 0.35,
      baseAboveGroundTiles: 0,
      widthTiles: 0.6,
      heightTiles: 0.8,
      ramp: 'iron_black',
      accentRamp: 'fire',
    },
  ],
  life: {
    frames: 8,
    effects: [
      {
        kind: 'banner_sway',
        col: 5.5,
        baseAboveGroundTiles: 1.6,
        widthTiles: 0.6,
        heightTiles: 1.2,
        ramp: 'banner_blue',
        cycles: 1,
        phase: 0,
      },
      {
        kind: 'brazier_flame',
        col: 0.42,
        baseAboveGroundTiles: 0.75,
        widthTiles: 0.45,
        heightTiles: 0.6,
        ramp: 'fire',
        cycles: 1,
        phase: 0.4,
      },
    ],
  },
};

/** Cartwright's Workshop — wide doors, a lean-to, and wheels against the wall. */
const CARTWRIGHTS_WORKSHOP: BuildingSpec = {
  key: 'cartwrights_workshop',
  file: 'cartwrights_workshop.png',
  title: "Cartwright's Workshop",
  replaces: 'village_house_4',
  tilesWide: 8,
  tilesHigh: 7,
  seed: SEED_CARTWRIGHT,
  stories: 1,
  sideReturnTiles: 0.6,
  facade: {
    ground: {
      material: 'timber_frame',
      ramp: 'sawn_pine',
      trimRamp: 'plaster_grey',
      grime: 0.26,
      moss: 0.12,
    },
    groundStoryTiles: 2.6,
    foundationTiles: 0.4,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 1.4,
        heightTiles: 0.16,
        ramp: 'oak_beam',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'shake',
    ramp: 'shake_brown',
    ridgeRamp: 'ridge_dark',
    depthTiles: 2.3,
    overhangTiles: 0.34,
    ridgeSagTiles: 0.05,
    mossy: false,
    disrepair: 0.14,
    chimneys: [{ col: 6.4, widthTiles: 0.45, heightTiles: 0.6, ramp: 'fieldstone', smokes: true }],
    dormers: [],
  },
  door: {
    col: 3,
    gapTiles: 2,
    paintedWidthTiles: 2.1,
    style: 'double',
    arch: 'flat_lintel',
    ramp: 'sawn_pine',
    hardware: true,
    stepTiles: 0.1,
  },
  windows: [
    {
      col: 1.2,
      baseAboveGroundTiles: 1.5,
      widthTiles: 0.8,
      heightTiles: 0.6,
      style: 'shuttered',
      lit: true,
      shutters: false,
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'lean_to',
      col: 5.6,
      baseAboveGroundTiles: 0,
      widthTiles: 1.3,
      heightTiles: 1.9,
      ramp: 'weathered_plank',
      accentRamp: 'shake_brown',
    },
    {
      kind: 'cart_wheel',
      col: 0.5,
      baseAboveGroundTiles: 0,
      widthTiles: 1.0,
      heightTiles: 1.0,
      ramp: 'sawn_pine',
      accentRamp: 'iron_black',
    },
    {
      kind: 'sawhorse',
      col: 5.4,
      baseAboveGroundTiles: 0,
      widthTiles: 0.9,
      heightTiles: 0.6,
      ramp: 'sawn_pine',
      accentRamp: 'oak_beam',
    },
    {
      kind: 'plank_stack',
      col: 1.7,
      baseAboveGroundTiles: 0,
      widthTiles: 1.1,
      heightTiles: 0.45,
      ramp: 'sawn_pine',
      accentRamp: 'oak_beam',
    },
  ],
  life: {
    frames: 6,
    effects: [
      {
        kind: 'chimney_smoke',
        col: 6.4,
        baseAboveGroundTiles: 6.0,
        widthTiles: 0.45,
        heightTiles: 1.6,
        ramp: 'smoke',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** Temple of the Sky — pale ashlar, a parapet, and a blue dome on a drum behind it. */
const TEMPLE: BuildingSpec = {
  key: 'temple',
  file: 'temple.png',
  title: 'Temple of the Sky',
  replaces: 'temple',
  tilesWide: 8,
  tilesHigh: 7,
  seed: SEED_TEMPLE,
  stories: 1,
  sideReturnTiles: 0.55,
  facade: {
    ground: {
      material: 'dressed_stone',
      ramp: 'pale_ashlar',
      trimRamp: 'pale_mortar',
      grime: 0.1,
      moss: 0.06,
    },
    groundStoryTiles: 3.2,
    foundationTiles: 0.55,
    quoins: true,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.26,
        heightTiles: 0.12,
        ramp: 'pale_ashlar',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 0.55,
        heightTiles: 0.18,
        ramp: 'pale_ashlar',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 1.42,
        heightTiles: 0.14,
        ramp: 'pale_mortar',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 2.32,
        heightTiles: 0.14,
        ramp: 'pale_ashlar',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 3.0,
        heightTiles: 0.08,
        ramp: 'brass_gold',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 3.1,
        heightTiles: 0.28,
        ramp: 'pale_ashlar',
        projecting: true,
      },
    ],
    pilasters: 5,
    pilasterRamp: 'pale_ashlar',
  },
  roof: {
    material: 'dome',
    ramp: 'dome_blue',
    ridgeRamp: 'brass_gold',
    // The roof plane has to hold a parapet, a drum and a dome stacked one on the
    // other; at the depth an ordinary pitched roof wants, the dome comes out a
    // saucer.
    depthTiles: 3.2,
    overhangTiles: 0.2,
    ridgeSagTiles: 0,
    mossy: false,
    disrepair: 0,
    chimneys: [],
    dormers: [],
  },
  door: {
    col: 3,
    gapTiles: 1,
    paintedWidthTiles: 1.3,
    style: 'gothic',
    arch: 'gothic',
    ramp: 'oak_beam',
    hardware: true,
    stepTiles: 0.3,
  },
  windows: [
    {
      col: 0.98,
      baseAboveGroundTiles: 1.32,
      widthTiles: 0.84,
      heightTiles: 1.6,
      style: 'arched',
      lit: true,
      shutters: false,
      flowerBox: false,
    },
    {
      col: 5.58,
      baseAboveGroundTiles: 1.32,
      widthTiles: 0.84,
      heightTiles: 1.6,
      style: 'arched',
      lit: true,
      shutters: false,
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'relief_board',
      col: 3.0,
      baseAboveGroundTiles: 2.85,
      widthTiles: 1.5,
      heightTiles: 0.72,
      ramp: 'pale_ashlar',
      accentRamp: 'brass_gold',
      device: 'sun_disc',
    },
    {
      kind: 'brazier',
      col: 1.9,
      baseAboveGroundTiles: 0,
      widthTiles: 0.6,
      heightTiles: 0.9,
      ramp: 'brass_gold',
      accentRamp: 'fire',
    },
    {
      kind: 'brazier',
      col: 5.2,
      baseAboveGroundTiles: 0,
      widthTiles: 0.6,
      heightTiles: 0.9,
      ramp: 'brass_gold',
      accentRamp: 'fire',
    },
  ],
  life: {
    frames: 6,
    effects: [
      {
        kind: 'brazier_flame',
        col: 1.97,
        baseAboveGroundTiles: 0.85,
        widthTiles: 0.45,
        heightTiles: 0.7,
        ramp: 'fire',
        cycles: 1,
        phase: 0,
      },
      {
        kind: 'brazier_flame',
        col: 5.27,
        baseAboveGroundTiles: 0.85,
        widthTiles: 0.45,
        heightTiles: 0.7,
        ramp: 'fire',
        cycles: 1,
        phase: 0.5,
      },
      {
        kind: 'finial_glint',
        col: 3.53,
        baseAboveGroundTiles: 6.3,
        widthTiles: 0.4,
        heightTiles: 0.5,
        ramp: 'brass_gold',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** Herb & Remedy — the apothecary, hung about with drying stems. */
const HERB_REMEDY: BuildingSpec = {
  key: 'herb_remedy',
  file: 'herb_remedy.png',
  title: 'Herb & Remedy',
  replaces: 'village_house_1',
  tilesWide: 7,
  tilesHigh: 6,
  seed: SEED_HERB,
  stories: 1,
  sideReturnTiles: 0.5,
  facade: {
    ground: {
      material: 'painted_plaster',
      ramp: 'plaster_cream',
      trimRamp: 'apothecary_sage',
      grime: 0.16,
      moss: 0.2,
    },
    groundStoryTiles: 2.2,
    foundationTiles: 0.42,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.42,
        heightTiles: 0.14,
        ramp: 'fieldstone',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'thatch',
    ramp: 'thatch_gold',
    ridgeRamp: 'ridge_thatch',
    depthTiles: 2.0,
    overhangTiles: 0.34,
    ridgeSagTiles: 0.05,
    mossy: true,
    disrepair: 0.1,
    chimneys: [
      { col: 5.2, widthTiles: 0.42, heightTiles: 0.58, ramp: 'fieldstone', smokes: false },
    ],
    dormers: [],
  },
  door: {
    col: 3,
    gapTiles: 1,
    paintedWidthTiles: 1.1,
    style: 'plank',
    arch: 'round',
    ramp: 'door_green',
    hardware: true,
    stepTiles: 0.14,
  },
  windows: [
    {
      col: 1.0,
      baseAboveGroundTiles: 1.3,
      widthTiles: 0.85,
      heightTiles: 0.65,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: true,
      interior: 'bottles',
    },
    {
      col: 4.9,
      baseAboveGroundTiles: 1.3,
      widthTiles: 0.85,
      heightTiles: 0.65,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: true,
      interior: 'bottles',
    },
  ],
  props: [
    {
      kind: 'relief_board',
      device: 'mortar_and_pestle',
      col: 2.6,
      baseAboveGroundTiles: 2.35,
      widthTiles: 1.2,
      heightTiles: 0.62,
      ramp: 'apothecary_sage',
      accentRamp: 'oak_beam',
    },
    {
      kind: 'vine',
      col: 5.5,
      baseAboveGroundTiles: 0,
      widthTiles: 0.7,
      heightTiles: 2.6,
      ramp: 'leaf_green',
      accentRamp: 'plaster_cream',
    },
  ],
  life: {
    frames: 7,
    effects: [
      {
        kind: 'hanging_sway',
        col: 1.9,
        baseAboveGroundTiles: 2.25,
        widthTiles: 1.3,
        heightTiles: 0.7,
        ramp: 'dried_herb',
        cycles: 1,
        phase: 0,
      },
      {
        kind: 'hanging_sway',
        col: 4.2,
        baseAboveGroundTiles: 2.35,
        widthTiles: 1.0,
        heightTiles: 0.6,
        ramp: 'dried_herb',
        cycles: 1,
        phase: 0.45,
      },
    ],
  },
};

/** General Store — the one true shopfront on the plaza. */
const GENERAL_STORE: BuildingSpec = {
  key: 'general_store',
  file: 'general_store.png',
  title: 'General Store',
  replaces: 'shop',
  tilesWide: 8,
  tilesHigh: 5,
  seed: SEED_STORE,
  stories: 1,
  sideReturnTiles: 0.55,
  facade: {
    ground: {
      material: 'timber_frame',
      ramp: 'oak_beam',
      trimRamp: 'plaster_cream',
      grime: 0.2,
      moss: 0.08,
    },
    groundStoryTiles: 2.1,
    foundationTiles: 0.35,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 2.0,
        heightTiles: 0.14,
        ramp: 'oak_beam',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'clay_tile',
    ramp: 'clay_terracotta',
    ridgeRamp: 'ridge_clay',
    depthTiles: 1.5,
    overhangTiles: 0.26,
    ridgeSagTiles: 0,
    mossy: false,
    disrepair: 0.08,
    chimneys: [
      { col: 6.5, widthTiles: 0.45, heightTiles: 0.55, ramp: 'fieldstone', smokes: false },
    ],
    dormers: [],
  },
  door: {
    col: 2,
    gapTiles: 2,
    paintedWidthTiles: 1.2,
    style: 'plank',
    arch: 'flat_lintel',
    ramp: 'oak_beam',
    hardware: true,
    stepTiles: 0.12,
  },
  windows: [
    {
      col: 3.7,
      baseAboveGroundTiles: 0.85,
      widthTiles: 2.4,
      heightTiles: 1.1,
      style: 'shopfront',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'goods',
    },
  ],
  props: [
    {
      kind: 'awning',
      col: 3.4,
      baseAboveGroundTiles: 2.0,
      widthTiles: 3.0,
      heightTiles: 0.5,
      ramp: 'awning_stripe',
      accentRamp: 'plaster_cream',
    },
    {
      kind: 'crate',
      col: 0.4,
      baseAboveGroundTiles: 0,
      widthTiles: 0.7,
      heightTiles: 0.55,
      ramp: 'sawn_pine',
      accentRamp: 'iron_black',
    },
    {
      kind: 'barrel',
      col: 1.3,
      baseAboveGroundTiles: 0,
      widthTiles: 0.5,
      heightTiles: 0.62,
      ramp: 'oak_beam',
      accentRamp: 'iron_black',
    },
    {
      kind: 'sack',
      col: 6.3,
      baseAboveGroundTiles: 0,
      widthTiles: 0.55,
      heightTiles: 0.5,
      ramp: 'hay_straw',
      accentRamp: 'weathered_plank',
    },
  ],
  life: {
    frames: 6,
    effects: [
      {
        kind: 'awning_ripple',
        col: 3.4,
        baseAboveGroundTiles: 1.78,
        widthTiles: 3.0,
        heightTiles: 0.22,
        ramp: 'awning_stripe',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** The Horned Flagon — the loud one on Market Row. */
const HORNED_FLAGON: BuildingSpec = {
  key: 'horned_flagon',
  file: 'horned_flagon.png',
  title: 'The Horned Flagon',
  replaces: 'tavern_2',
  tilesWide: 8,
  tilesHigh: 5,
  seed: SEED_FLAGON,
  stories: 2,
  sideReturnTiles: 0.55,
  facade: {
    ground: {
      material: 'coursed_stone',
      ramp: 'fieldstone',
      trimRamp: 'mortar',
      grime: 0.3,
      moss: 0.16,
    },
    upper: {
      material: 'timber_frame',
      ramp: 'oak_beam',
      trimRamp: 'plaster_cream',
      grime: 0.22,
      moss: 0,
    },
    groundStoryTiles: 1.4,
    foundationTiles: 0.32,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 1.32,
        heightTiles: 0.18,
        ramp: 'oak_beam',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'clay_tile',
    ramp: 'clay_red',
    ridgeRamp: 'ridge_clay',
    depthTiles: 1.5,
    overhangTiles: 0.28,
    ridgeSagTiles: 0.04,
    mossy: false,
    disrepair: 0.12,
    chimneys: [
      { col: 1.2, widthTiles: 0.5, heightTiles: 0.6, ramp: 'fieldstone', smokes: true },
      { col: 6.15, widthTiles: 0.42, heightTiles: 0.44, ramp: 'fieldstone', smokes: false },
    ],
    dormers: [{ col: 4.5, widthTiles: 0.9, lit: true }],
  },
  door: {
    col: 3,
    gapTiles: 2,
    paintedWidthTiles: 1.5,
    style: 'plank',
    arch: 'round',
    ramp: 'oak_beam',
    hardware: true,
    stepTiles: 0.12,
  },
  windows: [
    {
      col: 1.0,
      baseAboveGroundTiles: 0.6,
      widthTiles: 1.0,
      heightTiles: 0.7,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'crowd',
    },
    {
      col: 5.3,
      baseAboveGroundTiles: 0.6,
      widthTiles: 1.0,
      heightTiles: 0.7,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'crowd',
    },
    {
      col: 2.4,
      baseAboveGroundTiles: 1.6,
      widthTiles: 0.7,
      heightTiles: 0.6,
      style: 'mullioned',
      lit: false,
      shutters: true,
      shutterRamp: 'shutter_red',
      flowerBox: false,
    },
    {
      col: 5.55,
      baseAboveGroundTiles: 1.6,
      widthTiles: 0.7,
      heightTiles: 0.6,
      style: 'mullioned',
      lit: true,
      shutters: true,
      shutterRamp: 'shutter_red',
      flowerBox: true,
      interior: 'crowd',
    },
    {
      col: 2.32,
      baseAboveGroundTiles: 0.62,
      widthTiles: 0.62,
      heightTiles: 0.6,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'crowd',
    },
  ],
  props: [
    {
      kind: 'relief_board',
      col: 4.4,
      baseAboveGroundTiles: 1.55,
      widthTiles: 0.7,
      heightTiles: 0.7,
      ramp: 'oak_beam',
      accentRamp: 'brass_gold',
      device: 'horn',
    },
    {
      kind: 'barrel',
      col: 6.1,
      baseAboveGroundTiles: 0,
      widthTiles: 0.55,
      heightTiles: 0.66,
      ramp: 'oak_beam',
      accentRamp: 'iron_black',
    },
    {
      kind: 'barrel',
      col: 6.66,
      baseAboveGroundTiles: 0,
      widthTiles: 0.48,
      heightTiles: 0.58,
      ramp: 'oak_beam',
      accentRamp: 'iron_black',
    },
    {
      kind: 'barrel',
      col: 6.24,
      baseAboveGroundTiles: 0.66,
      widthTiles: 0.44,
      heightTiles: 0.5,
      ramp: 'oak_beam',
      accentRamp: 'iron_black',
    },
    {
      kind: 'firewood',
      col: 0.34,
      baseAboveGroundTiles: 0,
      widthTiles: 0.72,
      heightTiles: 0.52,
      ramp: 'stained_timber',
      accentRamp: 'oak_beam',
    },
    {
      kind: 'lantern',
      col: 2.72,
      baseAboveGroundTiles: 0.86,
      widthTiles: 0.32,
      heightTiles: 0.44,
      ramp: 'iron_black',
      accentRamp: 'hearth_glow',
    },
    {
      kind: 'lantern',
      col: 4.88,
      baseAboveGroundTiles: 0.86,
      widthTiles: 0.32,
      heightTiles: 0.44,
      ramp: 'iron_black',
      accentRamp: 'hearth_glow',
    },
    {
      kind: 'letter_board',
      col: 0.45,
      baseAboveGroundTiles: 1.66,
      widthTiles: 1.35,
      heightTiles: 0.38,
      ramp: 'stained_timber',
      accentRamp: 'brass_gold',
      label: 'ALE',
    },
  ],
  life: {
    // The longest loop in the town, and the only one that pays for its length.
    // A walker's speed is the width of the opening divided by the slice of the
    // loop it spends crossing, so a slow walk and a visible pause between walks
    // both come out of the same budget: 3 s buys roughly a tile a second across
    // the glass and still leaves over a second of empty window afterwards. The
    // taproom is the one building where a crowd has to read.
    frames: 24,
    effects: [
      {
        kind: 'window_crowd',
        col: 1.0,
        baseAboveGroundTiles: 0.6,
        widthTiles: 1.0,
        heightTiles: 0.7,
        ramp: 'hearth_glow',
        cycles: 1,
        phase: 0,
        walkers: 1,
      },
      {
        kind: 'window_crowd',
        col: 5.3,
        baseAboveGroundTiles: 0.6,
        widthTiles: 1.0,
        heightTiles: 0.7,
        ramp: 'hearth_glow',
        cycles: 1,
        phase: 0.5,
        walkers: 1,
      },
      {
        // Three cycles, not one: this loop is nearly three times the town's
        // others, and a single cycle across it would drift the smoke at a third
        // the rate every other chimney rises at.
        kind: 'chimney_smoke',
        col: 1.2,
        baseAboveGroundTiles: 4.0,
        widthTiles: 0.5,
        heightTiles: 1.2,
        ramp: 'smoke',
        cycles: 3,
        phase: 0,
      },
    ],
  },
};

/** Old Hilda's Cottage — the crooked one, sagging under moss-heavy thatch. */
const HILDAS_COTTAGE: BuildingSpec = {
  key: 'hildas_cottage',
  file: 'hildas_cottage.png',
  title: "Old Hilda's Cottage",
  replaces: 'village_house_3',
  tilesWide: 7,
  tilesHigh: 6,
  seed: SEED_HILDA,
  stories: 1,
  sideReturnTiles: 0.45,
  facade: {
    ground: {
      material: 'plaster',
      ramp: 'plaster_grey',
      trimRamp: 'fieldstone',
      grime: 0.36,
      moss: 0.3,
    },
    groundStoryTiles: 2.1,
    foundationTiles: 0.5,
    quoins: false,
    leanTiles: 0.1,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.5,
        heightTiles: 0.14,
        ramp: 'fieldstone',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'thatch',
    ramp: 'thatch_weathered',
    ridgeRamp: 'ridge_thatch',
    depthTiles: 2.2,
    overhangTiles: 0.28,
    ridgeSagTiles: 0.32,
    mossy: true,
    disrepair: 0.35,
    chimneys: [{ col: 5.0, widthTiles: 0.48, heightTiles: 0.7, ramp: 'fieldstone', smokes: true }],
    dormers: [],
  },
  door: {
    col: 3,
    gapTiles: 1,
    paintedWidthTiles: 1.05,
    style: 'plank',
    arch: 'flat_lintel',
    ramp: 'weathered_plank',
    hardware: true,
    stepTiles: 0.16,
  },
  windows: [
    {
      col: 1.2,
      baseAboveGroundTiles: 1.3,
      widthTiles: 0.7,
      heightTiles: 0.7,
      style: 'round',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'bottles',
    },
  ],
  props: [
    {
      kind: 'cauldron',
      col: 4.6,
      baseAboveGroundTiles: 0,
      widthTiles: 0.85,
      heightTiles: 0.8,
      ramp: 'iron_black',
      accentRamp: 'witch_smoke',
    },
    {
      kind: 'charm_string',
      col: 2.2,
      baseAboveGroundTiles: 1.6,
      widthTiles: 0.75,
      heightTiles: 0.9,
      ramp: 'weathered_plank',
      accentRamp: 'dried_herb',
    },
    {
      kind: 'herb_bundle',
      col: 4.1,
      baseAboveGroundTiles: 1.7,
      widthTiles: 0.55,
      heightTiles: 0.8,
      ramp: 'dried_herb',
      accentRamp: 'weathered_plank',
    },
  ],
  life: {
    frames: 7,
    effects: [
      {
        kind: 'chimney_smoke',
        col: 5.0,
        baseAboveGroundTiles: 5.0,
        widthTiles: 0.48,
        heightTiles: 1.5,
        ramp: 'witch_smoke',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** The Rusty Anvil — the smithy, with the forge open onto the side return. */
const BLACKSMITH: BuildingSpec = {
  key: 'blacksmith',
  file: 'blacksmith.png',
  title: 'The Rusty Anvil',
  replaces: 'blacksmith',
  tilesWide: 8,
  tilesHigh: 5,
  seed: SEED_SMITHY,
  stories: 1,
  sideReturnTiles: 0.5,
  facade: {
    ground: {
      material: 'coursed_stone',
      ramp: 'soot_stone',
      trimRamp: 'dark_mortar',
      grime: 0.45,
      moss: 0.06,
    },
    groundStoryTiles: 2.0,
    foundationTiles: 0.4,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.4,
        heightTiles: 0.16,
        ramp: 'soot_stone',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 1.7,
        heightTiles: 0.3,
        ramp: 'soot_stone',
        projecting: false,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'slate',
    ramp: 'slate_grey',
    ridgeRamp: 'ridge_dark',
    depthTiles: 1.4,
    overhangTiles: 0.3,
    ridgeSagTiles: 0.04,
    mossy: false,
    disrepair: 0.16,
    chimneys: [{ col: 5.9, widthTiles: 0.62, heightTiles: 0.8, ramp: 'soot_stone', smokes: true }],
    dormers: [],
  },
  door: {
    col: 4,
    gapTiles: 2,
    paintedWidthTiles: 1.3,
    style: 'plank',
    arch: 'flat_lintel',
    ramp: 'weathered_plank',
    hardware: true,
    stepTiles: 0.1,
  },
  windows: [
    {
      col: 6.2,
      baseAboveGroundTiles: 1.65,
      widthTiles: 0.6,
      heightTiles: 0.5,
      style: 'shuttered',
      lit: false,
      shutters: true,
      shutterRamp: 'weathered_plank',
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'forge_mouth',
      col: 1.1,
      baseAboveGroundTiles: 0,
      widthTiles: 1.5,
      heightTiles: 1.5,
      ramp: 'soot_stone',
      accentRamp: 'fire',
    },
    {
      kind: 'anvil',
      col: 2.9,
      baseAboveGroundTiles: 0,
      widthTiles: 0.8,
      heightTiles: 0.8,
      ramp: 'iron_black',
      accentRamp: 'oak_beam',
    },
    {
      kind: 'quench_barrel',
      col: 0.2,
      baseAboveGroundTiles: 0,
      widthTiles: 0.6,
      heightTiles: 0.62,
      ramp: 'oak_beam',
      accentRamp: 'iron_black',
    },
    {
      kind: 'tool_rack',
      col: 6.1,
      baseAboveGroundTiles: 0.7,
      widthTiles: 0.9,
      heightTiles: 0.8,
      ramp: 'iron_black',
      accentRamp: 'oak_beam',
    },
  ],
  life: {
    frames: 8,
    effects: [
      {
        kind: 'forge_pulse',
        col: 1.25,
        baseAboveGroundTiles: 0.15,
        widthTiles: 1.2,
        heightTiles: 1.1,
        ramp: 'fire',
        cycles: 1,
        phase: 0,
      },
      {
        kind: 'spark_motes',
        col: 1.25,
        baseAboveGroundTiles: 1.2,
        widthTiles: 1.2,
        heightTiles: 1.5,
        ramp: 'fire',
        cycles: 1,
        phase: 0.25,
      },
      {
        kind: 'chimney_smoke',
        col: 5.9,
        baseAboveGroundTiles: 4.0,
        widthTiles: 0.62,
        heightTiles: 1.1,
        ramp: 'smoke',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** The Sunken Stump Pub — settled into the mud, and proud of it. */
const SUNKEN_STUMP: BuildingSpec = {
  key: 'sunken_stump',
  file: 'sunken_stump.png',
  title: 'The Sunken Stump Pub',
  replaces: 'tavern_1',
  tilesWide: 8,
  tilesHigh: 5,
  seed: SEED_STUMP,
  stories: 1,
  sideReturnTiles: 0.5,
  facade: {
    ground: {
      material: 'plank',
      ramp: 'weathered_plank',
      trimRamp: 'dark_mortar',
      grime: 0.42,
      moss: 0.32,
    },
    groundStoryTiles: 2.0,
    foundationTiles: 0.3,
    quoins: false,
    leanTiles: 0.14,
    sinkTiles: 0.22,
    bands: [
      {
        baseAboveGroundTiles: 0.3,
        heightTiles: 0.12,
        ramp: 'weathered_plank',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'shake',
    ramp: 'shake_brown',
    ridgeRamp: 'ridge_dark',
    depthTiles: 1.6,
    overhangTiles: 0.32,
    ridgeSagTiles: 0.26,
    mossy: true,
    disrepair: 0.4,
    chimneys: [
      { col: 6.2, widthTiles: 0.45, heightTiles: 0.55, ramp: 'fieldstone', smokes: false },
    ],
    dormers: [],
  },
  door: {
    col: 2,
    gapTiles: 2,
    paintedWidthTiles: 1.3,
    style: 'plank',
    arch: 'flat_lintel',
    ramp: 'weathered_plank',
    hardware: true,
    stepTiles: -0.3,
  },
  windows: [
    {
      col: 4.4,
      baseAboveGroundTiles: 1.25,
      widthTiles: 0.9,
      heightTiles: 0.6,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'crowd',
    },
    {
      col: 6.0,
      baseAboveGroundTiles: 1.25,
      widthTiles: 0.8,
      heightTiles: 0.6,
      style: 'shuttered',
      lit: false,
      shutters: false,
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'boarded_window',
      col: 6.0,
      baseAboveGroundTiles: 1.25,
      widthTiles: 0.8,
      heightTiles: 0.6,
      ramp: 'weathered_plank',
      accentRamp: 'iron_black',
    },
    {
      kind: 'relief_board',
      device: 'tankard',
      col: 3.0,
      baseAboveGroundTiles: 1.62,
      widthTiles: 1.2,
      heightTiles: 0.82,
      ramp: 'weathered_plank',
      accentRamp: 'brass_gold',
    },
    {
      kind: 'barrel',
      col: 0.3,
      baseAboveGroundTiles: 0,
      widthTiles: 0.5,
      heightTiles: 0.58,
      ramp: 'weathered_plank',
      accentRamp: 'iron_black',
    },
  ],
  life: {
    frames: 6,
    effects: [
      {
        kind: 'lantern_flicker',
        col: 3.3,
        baseAboveGroundTiles: 1.55,
        widthTiles: 0.4,
        heightTiles: 0.75,
        ramp: 'hearth_glow',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** Signet's Ink — the most colourful wall in the Low Quarter. */
const SIGNETS_INK: BuildingSpec = {
  key: 'signets_ink',
  file: 'signets_ink.png',
  title: "Signet's Ink",
  replaces: 'tattoo_parlor',
  tilesWide: 8,
  tilesHigh: 5,
  seed: SEED_SIGNET,
  stories: 1,
  sideReturnTiles: 0.5,
  facade: {
    ground: {
      material: 'painted_plaster',
      ramp: 'plaster_grey',
      trimRamp: 'ink_violet',
      grime: 0.2,
      moss: 0.08,
    },
    groundStoryTiles: 2.2,
    foundationTiles: 0.34,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.9,
        heightTiles: 0.2,
        ramp: 'ink_violet',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 1.98,
        heightTiles: 0.12,
        ramp: 'brass_gold',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 2.32,
        heightTiles: 0.18,
        ramp: 'brass_gold',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 0.34,
        heightTiles: 0.12,
        ramp: 'brass_gold',
        projecting: true,
      },
    ],
    pilasters: 6,
    pilasterRamp: 'ink_violet',
  },
  roof: {
    material: 'clay_tile',
    ramp: 'clay_terracotta',
    ridgeRamp: 'ridge_clay',
    depthTiles: 1.5,
    overhangTiles: 0.26,
    ridgeSagTiles: 0,
    mossy: false,
    disrepair: 0.1,
    chimneys: [{ col: 1.1, widthTiles: 0.42, heightTiles: 0.5, ramp: 'fieldstone', smokes: false }],
    dormers: [],
  },
  door: {
    col: 2,
    gapTiles: 1,
    paintedWidthTiles: 1.15,
    style: 'curtained',
    arch: 'round',
    ramp: 'ink_violet',
    hardware: false,
    stepTiles: 0.12,
  },
  windows: [
    {
      col: 3.64,
      baseAboveGroundTiles: 0.86,
      widthTiles: 1.72,
      heightTiles: 1.04,
      style: 'shopfront',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'flash_art',
    },
    {
      col: 6.0,
      baseAboveGroundTiles: 1.2,
      widthTiles: 0.7,
      heightTiles: 0.6,
      style: 'mullioned',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'bottles',
    },
    {
      col: 0.42,
      baseAboveGroundTiles: 0.92,
      widthTiles: 1.22,
      heightTiles: 0.98,
      style: 'shopfront',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'flash_art',
    },
  ],
  props: [
    {
      kind: 'letter_board',
      col: 3.5,
      baseAboveGroundTiles: 2.05,
      widthTiles: 2.0,
      heightTiles: 0.42,
      ramp: 'ink_violet',
      accentRamp: 'brass_gold',
      label: 'INK',
    },
    {
      kind: 'awning',
      col: 0.32,
      baseAboveGroundTiles: 1.96,
      widthTiles: 1.42,
      heightTiles: 0.38,
      ramp: 'awning_stripe',
      accentRamp: 'ink_violet',
    },
    {
      kind: 'lantern',
      col: 1.52,
      baseAboveGroundTiles: 1.42,
      widthTiles: 0.32,
      heightTiles: 0.46,
      ramp: 'brass_gold',
      accentRamp: 'hearth_glow',
    },
    {
      kind: 'lantern',
      col: 3.18,
      baseAboveGroundTiles: 1.42,
      widthTiles: 0.32,
      heightTiles: 0.46,
      ramp: 'brass_gold',
      accentRamp: 'hearth_glow',
    },
    {
      kind: 'letter_board',
      col: 5.82,
      baseAboveGroundTiles: 1.94,
      widthTiles: 1.05,
      heightTiles: 0.32,
      ramp: 'ink_violet',
      accentRamp: 'brass_gold',
      label: 'FLASH',
    },
    {
      kind: 'crate',
      col: 5.6,
      baseAboveGroundTiles: 0,
      widthTiles: 0.6,
      heightTiles: 0.55,
      ramp: 'oak_beam',
      accentRamp: 'ink_violet',
    },
    {
      kind: 'crate',
      col: 5.72,
      baseAboveGroundTiles: 0.55,
      widthTiles: 0.44,
      heightTiles: 0.4,
      ramp: 'oak_beam',
      accentRamp: 'brass_gold',
    },
    {
      kind: 'rope_line',
      col: 6.55,
      baseAboveGroundTiles: 0,
      widthTiles: 1.15,
      heightTiles: 0.65,
      ramp: 'brass_gold',
      accentRamp: 'ink_violet',
    },
  ],
  life: {
    frames: 8,
    effects: [
      {
        kind: 'bead_curtain_sway',
        col: 2.05,
        baseAboveGroundTiles: 0.05,
        widthTiles: 0.9,
        heightTiles: 1.3,
        ramp: 'brass_gold',
        cycles: 1,
        phase: 0,
      },
      {
        kind: 'window_breathe',
        col: 3.64,
        baseAboveGroundTiles: 0.86,
        widthTiles: 1.72,
        heightTiles: 1.04,
        ramp: 'hearth_glow',
        cycles: 1,
        phase: 0.5,
      },
    ],
  },
};

/** The Desperado Club — the biggest canvas in the town, and the loudest. */
const DESPERADO_CLUB: BuildingSpec = {
  key: 'desperado_club',
  file: 'desperado_club.png',
  title: 'The Desperado Club',
  replaces: 'desperado_club',
  tilesWide: 12,
  tilesHigh: 10,
  seed: SEED_DESPERADO,
  stories: 2,
  sideReturnTiles: 0.7,
  facade: {
    ground: {
      material: 'dressed_stone',
      ramp: 'dark_dressed_stone',
      trimRamp: 'dark_mortar',
      grime: 0.18,
      moss: 0.05,
    },
    upper: {
      material: 'dressed_stone',
      ramp: 'dark_dressed_stone',
      trimRamp: 'dark_mortar',
      grime: 0.12,
      moss: 0,
    },
    groundStoryTiles: 3.0,
    foundationTiles: 0.7,
    quoins: true,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.7,
        heightTiles: 0.24,
        ramp: 'dark_dressed_stone',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 3.0,
        heightTiles: 0.3,
        ramp: 'dark_dressed_stone',
        projecting: true,
      },
      {
        baseAboveGroundTiles: 5.8,
        heightTiles: 0.3,
        ramp: 'brass_gold',
        projecting: true,
      },
    ],
    pilasters: 6,
    pilasterRamp: 'dark_dressed_stone',
  },
  roof: {
    material: 'slate',
    ramp: 'slate_grey',
    ridgeRamp: 'ridge_dark',
    depthTiles: 2.4,
    overhangTiles: 0.32,
    ridgeSagTiles: 0,
    mossy: false,
    disrepair: 0.03,
    chimneys: [
      { col: 1.6, widthTiles: 0.6, heightTiles: 0.9, ramp: 'dark_dressed_stone', smokes: true },
      { col: 9.6, widthTiles: 0.6, heightTiles: 0.8, ramp: 'dark_dressed_stone', smokes: false },
    ],
    dormers: [
      { col: 4.2, widthTiles: 1.0, lit: true },
      { col: 7.0, widthTiles: 1.0, lit: true },
    ],
  },
  door: {
    col: 4,
    gapTiles: 2,
    paintedWidthTiles: 2.6,
    style: 'grand',
    arch: 'round',
    ramp: 'oak_beam',
    hardware: true,
    stepTiles: 0.34,
  },
  windows: [
    {
      col: 1.2,
      baseAboveGroundTiles: 1.2,
      widthTiles: 1.0,
      heightTiles: 1.2,
      style: 'arched',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'crowd',
    },
    {
      col: 9.2,
      baseAboveGroundTiles: 1.2,
      widthTiles: 1.0,
      heightTiles: 1.2,
      style: 'arched',
      lit: true,
      shutters: false,
      flowerBox: false,
      interior: 'crowd',
    },
    {
      col: 2.5,
      baseAboveGroundTiles: 3.6,
      widthTiles: 0.9,
      heightTiles: 1.0,
      style: 'arched',
      lit: true,
      shutters: false,
      flowerBox: false,
    },
    {
      col: 8.2,
      baseAboveGroundTiles: 3.6,
      widthTiles: 0.9,
      heightTiles: 1.0,
      style: 'arched',
      lit: false,
      shutters: false,
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'letter_board',
      col: 3.6,
      baseAboveGroundTiles: 4.9,
      widthTiles: 4.6,
      heightTiles: 0.8,
      ramp: 'dark_dressed_stone',
      accentRamp: 'brass_gold',
      label: 'DESPERADO',
    },
    {
      kind: 'rope_line',
      col: 2.4,
      baseAboveGroundTiles: 0,
      widthTiles: 2.2,
      heightTiles: 0.8,
      ramp: 'banner_red',
      accentRamp: 'brass_gold',
    },
    {
      kind: 'rope_line',
      col: 7.2,
      baseAboveGroundTiles: 0,
      widthTiles: 2.2,
      heightTiles: 0.8,
      ramp: 'banner_red',
      accentRamp: 'brass_gold',
    },
    {
      kind: 'suit_lantern',
      col: 3.3,
      baseAboveGroundTiles: 2.6,
      widthTiles: 0.55,
      heightTiles: 0.7,
      ramp: 'brass_gold',
      accentRamp: 'iron_black',
    },
    {
      kind: 'suit_lantern',
      col: 8.1,
      baseAboveGroundTiles: 2.6,
      widthTiles: 0.55,
      heightTiles: 0.7,
      ramp: 'brass_gold',
      accentRamp: 'iron_black',
    },
  ],
  life: {
    frames: 6,
    effects: [
      {
        kind: 'suit_lantern_sequence',
        col: 3.1,
        baseAboveGroundTiles: 2.65,
        widthTiles: 5.6,
        heightTiles: 0.6,
        ramp: 'brass_gold',
        cycles: 1,
        phase: 0,
      },
      {
        kind: 'window_crowd',
        col: 1.2,
        baseAboveGroundTiles: 1.2,
        widthTiles: 1.0,
        heightTiles: 1.2,
        ramp: 'hearth_glow',
        cycles: 1,
        phase: 0.25,
      },
      {
        kind: 'chimney_smoke',
        col: 1.6,
        baseAboveGroundTiles: 8.0,
        widthTiles: 0.6,
        heightTiles: 1.8,
        ramp: 'smoke',
        cycles: 1,
        phase: 0,
      },
    ],
  },
};

/** Miller's Farm — the farmhouse against the south-east wall. */
const MILLERS_FARM: BuildingSpec = {
  key: 'millers_farm',
  file: 'millers_farm.png',
  title: "Miller's Farm",
  replaces: 'village_house_4',
  tilesWide: 8,
  tilesHigh: 7,
  seed: SEED_MILL,
  stories: 1,
  sideReturnTiles: 0.55,
  facade: {
    ground: {
      material: 'plaster',
      ramp: 'plaster_cream',
      trimRamp: 'fieldstone',
      grime: 0.36,
      moss: 0.3,
    },
    groundStoryTiles: 2.6,
    foundationTiles: 0.6,
    quoins: false,
    leanTiles: 0,
    sinkTiles: 0,
    bands: [
      {
        baseAboveGroundTiles: 0.6,
        heightTiles: 0.16,
        ramp: 'fieldstone',
        projecting: true,
      },
    ],
    pilasters: 0,
  },
  roof: {
    material: 'thatch',
    ramp: 'thatch_gold',
    ridgeRamp: 'ridge_thatch',
    depthTiles: 2.3,
    overhangTiles: 0.36,
    ridgeSagTiles: 0.08,
    mossy: false,
    disrepair: 0.14,
    chimneys: [{ col: 1.5, widthTiles: 0.5, heightTiles: 0.65, ramp: 'fieldstone', smokes: true }],
    dormers: [{ col: 5.4, widthTiles: 0.9, lit: false }],
  },
  door: {
    col: 3,
    gapTiles: 1,
    paintedWidthTiles: 1.1,
    style: 'plank',
    arch: 'flat_lintel',
    ramp: 'oak_beam',
    hardware: true,
    stepTiles: 0.14,
  },
  windows: [
    {
      col: 1.2,
      baseAboveGroundTiles: 1.5,
      widthTiles: 0.8,
      heightTiles: 0.65,
      style: 'shuttered',
      lit: true,
      shutters: true,
      shutterRamp: 'shutter_green',
      flowerBox: true,
    },
    {
      col: 5.0,
      baseAboveGroundTiles: 1.5,
      widthTiles: 0.8,
      heightTiles: 0.65,
      style: 'shuttered',
      lit: false,
      shutters: true,
      shutterRamp: 'shutter_green',
      flowerBox: false,
    },
  ],
  props: [
    {
      kind: 'hay_bale',
      col: 5.5,
      baseAboveGroundTiles: 0,
      widthTiles: 1.0,
      heightTiles: 0.8,
      ramp: 'hay_straw',
      accentRamp: 'weathered_plank',
    },
    {
      kind: 'grain_sack',
      col: 0.4,
      baseAboveGroundTiles: 0,
      widthTiles: 0.6,
      heightTiles: 0.7,
      ramp: 'hay_straw',
      accentRamp: 'weathered_plank',
    },
    {
      kind: 'pitchfork',
      col: 1.6,
      baseAboveGroundTiles: 0,
      widthTiles: 0.3,
      heightTiles: 1.5,
      ramp: 'weathered_plank',
      accentRamp: 'iron_black',
    },
    {
      kind: 'relief_board',
      device: 'wheat_sheaf',
      col: 2.65,
      baseAboveGroundTiles: 2.3,
      widthTiles: 1.3,
      heightTiles: 0.85,
      ramp: 'oak_beam',
      accentRamp: 'hay_straw',
    },
    {
      kind: 'weathervane',
      col: 3.5,
      baseAboveGroundTiles: 5.96,
      widthTiles: 0.7,
      heightTiles: 0.6,
      ramp: 'iron_black',
      accentRamp: 'brass_gold',
    },
  ],
  life: {
    frames: 7,
    effects: [
      {
        kind: 'chimney_smoke',
        col: 1.5,
        baseAboveGroundTiles: 6.0,
        widthTiles: 0.5,
        heightTiles: 1.6,
        ramp: 'smoke',
        cycles: 1,
        phase: 0,
      },
      {
        kind: 'weathervane_swing',
        col: 3.5,
        baseAboveGroundTiles: 6.0,
        widthTiles: 0.7,
        heightTiles: 0.55,
        ramp: 'iron_black',
        cycles: 1,
        phase: 0.3,
      },
    ],
  },
};

/**
 * Every building this generator owns, in the order they are baked.
 *
 * The inn is first because it was the pilot: when a shared pass is changed, its
 * effect shows up in the first contact sheet rendered rather than the eighth.
 */
export const BUILDING_SPECS: ReadonlyArray<BuildingSpec> = [
  SLEEPING_CAT_INN,
  BLACKWOOD_LODGE,
  SHEPHERDS_CABIN,
  BARRACKS,
  CARTWRIGHTS_WORKSHOP,
  TEMPLE,
  HERB_REMEDY,
  GENERAL_STORE,
  HORNED_FLAGON,
  HILDAS_COTTAGE,
  BLACKSMITH,
  SUNKEN_STUMP,
  SIGNETS_INK,
  DESPERADO_CLUB,
  MILLERS_FARM,
];

export function findBuildingSpec(key: string): BuildingSpec {
  const found = BUILDING_SPECS.find((spec) => spec.key === key);
  if (found === undefined) throw new Error(`No building spec for key '${key}'`);
  return found;
}
