/**
 * The catalogue against the built layouts, for `verify:construction-contracts`:
 * every spot resolves onto the building it names, on the kind of surface it
 * claims, without sharing a target with another spot; no excluded building
 * hosts a contract; and every pool offers enough distinct contracts.
 *
 * Skyfowl Town rooms are generated by `GameMap.generateInterior` from each
 * world seed's own building entries; Briar Hollow is read from each seed's
 * own `BriarHollowSite`. A negative section breaks one layout id in memory
 * and proves the check names the building and the spot.
 */

import { TILE_SIZE } from '../../src/core/constants';
import { GameMap } from '../../src/map/GameMap';
import { CONTRACT_PROP_ID_PREFIX } from '../../src/map/contractAreas';
import type { BuildingEntry } from '../../src/map/OverworldGenerator';
import type { BriarHollowSite, VillageBuildingDef } from '../../src/map/overworld/briarHollowSite';
import type { TileRect } from '../../src/map/town/townPlan';
import { INTERIOR_FLOOR_TYPES, INTERIOR_WALL } from '../../src/map/tileTypes';
import { level3 } from '../../src/levels/level3';
import { TOWN_INTERIOR_PROPS } from '../../src/sprites/art/townInterior/townInteriorProps';
import {
  CONTRACT_EXCLUDED_TOWN_BUILDINGS,
  CONTRACT_SITES,
  skyfowlContractSite,
  type BriarHollowContractSiteDef,
  type ContractSiteDef,
  type ContractSpotDef,
  type SkyfowlContractSiteDef,
} from '../../src/systems/constructionContracts/contractCatalog';
import {
  CONTRACT_MATERIAL_BANDS,
  CONTRACT_MAX_SPOTS,
  CONTRACT_MIN_DISTINCT_SETS,
  CONTRACT_MIN_SPOTS,
  validSpotSets,
} from '../../src/systems/constructionContracts/contractGenerator';
import {
  briarHollowSpotFootprint,
  footprintTiles,
  skyfowlSpotFootprint,
  type ContractSpotFootprint,
} from '../../src/systems/constructionContracts/contractTargets';
import { CONTRACT_MATERIALS, type Check } from './shared';

/** World seeds whose town entries and village are each checked in full. */
const LAYOUT_WORLD_COUNT = 4;
export const LAYOUT_WORLD_SEEDS: readonly number[] = Array.from(
  { length: LAYOUT_WORLD_COUNT },
  (_, world) => world + 1,
);

/** Skyfowl Town sites the town plan builds: every enterable building but the three excluded. */
const EXPECTED_SKYFOWL_SITES = 13;
/** Every Briar Hollow building. */
const EXPECTED_VILLAGE_SITES = 15;

/** The interior grid a Skyfowl Town spot resolves in; a view so a negative check can swap an id. */
type InteriorLayout = Pick<GameMap, 'placedInteriorProps' | 'structure'>;

interface SkyfowlSiteLayout {
  readonly town: 'skyfowl';
  readonly site: SkyfowlContractSiteDef;
  readonly map: InteriorLayout;
}

interface VillageSiteLayout {
  readonly town: 'briar_hollow';
  readonly site: BriarHollowContractSiteDef;
  readonly village: BriarHollowSite;
}

type SiteLayout = SkyfowlSiteLayout | VillageSiteLayout;

export interface WorldLayouts {
  readonly seed: number;
  readonly entries: readonly BuildingEntry[];
  readonly village: BriarHollowSite;
  /** The overworld the village stands on, for walking it. */
  readonly map: GameMap;
}

const worldCache = new Map<number, WorldLayouts>();

/** The building entries and village one world seed generates, built once per seed. */
export function worldLayouts(seed: number): WorldLayouts {
  const cached = worldCache.get(seed);
  if (cached !== undefined) return cached;
  const map = new GameMap({
    mapSize: level3.mapSize,
    tileHeight: TILE_SIZE,
    mapType: 'overworld',
    worldSeed: seed,
  });
  const village = map.briarHollow;
  if (village === null) throw new Error(`world seed ${seed} has no Briar Hollow`);
  const world: WorldLayouts = { seed, entries: map.buildingEntries, village, map };
  worldCache.set(seed, world);
  return world;
}

/** The ground floor of a Skyfowl Town building, generated the way its interior scene generates it. */
export function generateGroundFloor(entry: BuildingEntry): GameMap {
  const map = new GameMap({ tileHeight: TILE_SIZE, prebuiltStructure: [] });
  map.generateInterior(entry.type, 0, entry.name, entry.hasSafeRoom === true);
  return map;
}

function siteLayout(site: ContractSiteDef, world: WorldLayouts): SiteLayout | string {
  if (site.town === 'briar_hollow') return { town: 'briar_hollow', site, village: world.village };
  const entry = world.entries.find((candidate) => candidate.name === site.buildingName);
  if (entry === undefined) return `${site.name}: no building entry on world seed ${world.seed}`;
  return { town: 'skyfowl', site, map: generateGroundFloor(entry) };
}

function rectsOverlap(a: TileRect, b: TileRect): boolean {
  return a.x < b.x + b.w && b.x < a.x + a.w && a.y < b.y + b.h && b.y < a.y + a.h;
}

function rectContains(rect: TileRect, x: number, y: number): boolean {
  return x >= rect.x && x < rect.x + rect.w && y >= rect.y && y < rect.y + rect.h;
}

function placedPropRect(prop: InteriorLayout['placedInteriorProps'][number]): TileRect {
  const { footprint } = TOWN_INTERIOR_PROPS[prop.propId];
  return { x: prop.tile.x, y: prop.tile.y, w: footprint.w, h: footprint.h };
}

const ORTHOGONAL_STEPS: ReadonlyArray<{ readonly dx: number; readonly dy: number }> = [
  { dx: 1, dy: 0 },
  { dx: -1, dy: 0 },
  { dx: 0, dy: 1 },
  { dx: 0, dy: -1 },
];

// ── Skyfowl Town surfaces ────────────────────────────────────────────────

function interiorTileType(map: InteriorLayout, x: number, y: number): number | undefined {
  return map.structure[y]?.[x]?.type;
}

function isInteriorFloor(map: InteriorLayout, x: number, y: number): boolean {
  const type = interiorTileType(map, x, y);
  return type !== undefined && INTERIOR_FLOOR_TYPES.has(type);
}

/** Why a tile is the wrong surface for a Skyfowl Town area of `surface`, or null when it is right. */
function interiorSurfaceFault(
  map: InteriorLayout,
  surface: ContractSpotFootprint['surface'],
  x: number,
  y: number,
): string | null {
  switch (surface) {
    case 'prop':
      return null;
    case 'floor': {
      if (!isInteriorFloor(map, x, y)) {
        return `tile (${x},${y}) is type ${String(interiorTileType(map, x, y))}, not plain floor`;
      }
      // A walkable prop (a dais, a rug of boards) is floor the party stands on.
      const prop = map.placedInteriorProps.find(
        (placed) =>
          !TOWN_INTERIOR_PROPS[placed.propId].walkable &&
          rectContains(placedPropRect(placed), x, y),
      );
      return prop === undefined ? null : `tile (${x},${y}) lies under blocking prop ${prop.id}`;
    }
    case 'wall': {
      if (interiorTileType(map, x, y) !== INTERIOR_WALL) return `tile (${x},${y}) is not a wall`;
      // The face only shows where the wall looks south into the room.
      return isInteriorFloor(map, x, y + 1) ? null : `wall tile (${x},${y}) shows no face`;
    }
    case 'doorway': {
      if (!isInteriorFloor(map, x, y)) return `doorway tile (${x},${y}) is not walkable floor`;
      const besideWall = ORTHOGONAL_STEPS.some(
        ({ dx, dy }) => interiorTileType(map, x + dx, y + dy) === INTERIOR_WALL,
      );
      return besideWall ? null : `doorway tile (${x},${y}) is not in a wall`;
    }
    case 'open_side':
      return 'a Skyfowl Town room has no open side';
  }
}

// ── Briar Hollow surfaces ────────────────────────────────────────────────

function isDoorwayTile(building: VillageBuildingDef, x: number, y: number): boolean {
  return building.doorways.some((door) => door.x === x && door.y === y);
}

function onPerimeter(rect: TileRect, x: number, y: number): boolean {
  if (!rectContains(rect, x, y)) return false;
  return x === rect.x || y === rect.y || x === rect.x + rect.w - 1 || y === rect.y + rect.h - 1;
}

function isCorner(rect: TileRect, x: number, y: number): boolean {
  const onWestOrEast = x === rect.x || x === rect.x + rect.w - 1;
  const onNorthOrSouth = y === rect.y || y === rect.y + rect.h - 1;
  return onWestOrEast && onNorthOrSouth;
}

/** Why a tile is the wrong surface for a Briar Hollow area of `surface`, or null when it is right. */
function villageSurfaceFault(
  village: BriarHollowSite,
  building: VillageBuildingDef,
  surface: ContractSpotFootprint['surface'],
  x: number,
  y: number,
): string | null {
  switch (surface) {
    case 'prop':
      return null;
    case 'floor': {
      if (isDoorwayTile(building, x, y)) return `floor tile (${x},${y}) is a threshold`;
      if (rectContains(building.interior, x, y)) {
        const prop = building.furniture.find((placed) =>
          rectContains({ x: placed.x, y: placed.y, w: placed.w, h: placed.h }, x, y),
        );
        return prop === undefined ? null : `floor tile (${x},${y}) lies under ${prop.prop}`;
      }
      // A door step: open ground just outside one of the building's doorways.
      const atDoor = ORTHOGONAL_STEPS.some(({ dx, dy }) => isDoorwayTile(building, x + dx, y + dy));
      const inAnyBuilding = village.buildings.some((other) => rectContains(other.rect, x, y));
      return atDoor && !inAnyBuilding
        ? null
        : `floor tile (${x},${y}) is neither inside the walls nor a door step`;
    }
    case 'wall':
      if (!onPerimeter(building.rect, x, y)) return `wall tile (${x},${y}) is off the wall line`;
      if (isDoorwayTile(building, x, y)) return `wall tile (${x},${y}) is a doorway`;
      return isCorner(building.rect, x, y) ? `wall tile (${x},${y}) is a corner post` : null;
    case 'doorway':
    case 'open_side':
      return isDoorwayTile(building, x, y) ? null : `${surface} tile (${x},${y}) is not an opening`;
  }
}

// ── One site ─────────────────────────────────────────────────────────────

function propCount(layout: SiteLayout, placedId: string): number {
  if (layout.town === 'skyfowl') {
    return layout.map.placedInteriorProps.filter((prop) => prop.id === placedId).length;
  }
  return layout.village.buildings
    .flatMap((building) => building.furniture)
    .filter((prop) => prop.contractSpotId === placedId).length;
}

function footprintOf(layout: SiteLayout, spot: ContractSpotDef): ContractSpotFootprint | null {
  return layout.town === 'skyfowl'
    ? skyfowlSpotFootprint(layout.site, spot, layout.map)
    : briarHollowSpotFootprint(layout.site, spot, layout.village);
}

/** Every contract-prop id the building's own layout carries. */
function layoutContractPropIds(layout: SiteLayout): string[] {
  if (layout.town === 'skyfowl') {
    return layout.map.placedInteriorProps
      .map((prop) => prop.id)
      .filter((id) => id.startsWith(CONTRACT_PROP_ID_PREFIX));
  }
  const building = layout.village.buildings.find((b) => b.id === layout.site.buildingId);
  return (building?.furniture ?? []).flatMap((prop) =>
    prop.contractSpotId === undefined ? [] : [prop.contractSpotId],
  );
}

/**
 * Every way the site's pool disagrees with its built layout, each naming the
 * building and the spot. Empty when every spot resolves exactly once, on the
 * right kind of surface, with no two spots sharing a tile.
 */
function siteTargetProblems(layout: SiteLayout): string[] {
  const { site } = layout;
  const problems: string[] = [];
  const where = (spot: ContractSpotDef): string => `${site.name}, spot "${spot.id}"`;
  const building =
    layout.town === 'briar_hollow'
      ? layout.village.buildings.find((candidate) => candidate.id === layout.site.buildingId)
      : undefined;
  if (layout.town === 'briar_hollow' && building === undefined) {
    return [`${site.name}: building ${layout.site.buildingId} missing from the village`];
  }
  const resolved: Array<{ spot: ContractSpotDef; footprint: ContractSpotFootprint }> = [];
  for (const spot of site.spots) {
    const target = spot.target;
    if (target.kind === 'prop') {
      const count = propCount(layout, target.placedId);
      if (count !== 1) {
        problems.push(`${where(spot)}: prop id ${target.placedId} found ${count} times, not once`);
        continue;
      }
    }
    const footprint = footprintOf(layout, spot);
    if (footprint === null) {
      problems.push(`${where(spot)}: target does not resolve in the built layout`);
      continue;
    }
    const expectedSurface = target.kind === 'prop' ? 'prop' : 'an area';
    if ((footprint.surface === 'prop') !== (target.kind === 'prop')) {
      problems.push(
        `${where(spot)}: resolved as ${footprint.surface}, expected ${expectedSurface}`,
      );
    }
    for (const tile of footprintTiles(footprint.rect)) {
      const fault =
        layout.town === 'skyfowl'
          ? interiorSurfaceFault(layout.map, footprint.surface, tile.x, tile.y)
          : building === undefined
            ? null
            : villageSurfaceFault(layout.village, building, footprint.surface, tile.x, tile.y);
      if (fault !== null) {
        problems.push(`${where(spot)} (${footprint.surface}): ${fault}`);
        break;
      }
    }
    resolved.push({ spot, footprint });
  }
  for (let i = 0; i < resolved.length; i++) {
    for (let j = i + 1; j < resolved.length; j++) {
      const a = resolved[i];
      const b = resolved[j];
      if (rectsOverlap(a.footprint.rect, b.footprint.rect)) {
        problems.push(`${site.name}: spots "${a.spot.id}" and "${b.spot.id}" overlap`);
      }
    }
  }
  const targetedIds = new Set(
    site.spots.flatMap((spot) => (spot.target.kind === 'prop' ? [spot.target.placedId] : [])),
  );
  for (const id of layoutContractPropIds(layout)) {
    if (!targetedIds.has(id))
      problems.push(`${site.name}: layout id ${id} names no catalogue spot`);
  }
  return problems;
}

function reportSite(check: Check, label: string, problems: readonly string[]): void {
  for (const problem of problems) console.log(`         ${problem}`);
  check(problems.length === 0, label);
}

// ── Deliberate breaks ────────────────────────────────────────────────────

/** A layout with one thing knocked out of it, and the building and spot the check must then name. */
interface LayoutBreak {
  readonly description: string;
  readonly siteName: string;
  readonly spotId: string;
  apply(layout: SiteLayout): SiteLayout;
}

function firstPropSpot(town: ContractSiteDef['town']): {
  site: ContractSiteDef;
  spot: ContractSpotDef;
} {
  for (const site of CONTRACT_SITES) {
    if (site.town !== town) continue;
    const spot = site.spots.find((candidate) => candidate.target.kind === 'prop');
    if (spot !== undefined) return { site, spot };
  }
  throw new Error(`no ${town} prop spot to break`);
}

function firstDoorwaySpot(): { site: BriarHollowContractSiteDef; spot: ContractSpotDef } {
  for (const site of CONTRACT_SITES) {
    if (site.town !== 'briar_hollow') continue;
    const village = worldLayouts(LAYOUT_WORLD_SEEDS[0]).village;
    const spot = site.spots.find(
      (candidate) => briarHollowSpotFootprint(site, candidate, village)?.surface === 'doorway',
    );
    if (spot !== undefined) return { site, spot };
  }
  throw new Error('no Briar Hollow doorway spot to break');
}

const BROKEN_ID_SUFFIX = ':broken';

function layoutBreaks(): LayoutBreak[] {
  const interior = firstPropSpot('skyfowl');
  const village = firstPropSpot('briar_hollow');
  const doorway = firstDoorwaySpot();
  const renameProp = (layout: SiteLayout, placedId: string): SiteLayout => {
    if (layout.town === 'skyfowl') {
      const map: InteriorLayout = {
        structure: layout.map.structure,
        placedInteriorProps: layout.map.placedInteriorProps.map((prop) =>
          prop.id === placedId ? { ...prop, id: `${prop.id}${BROKEN_ID_SUFFIX}` } : prop,
        ),
      };
      return { ...layout, map };
    }
    const buildings = layout.village.buildings.map((building) => ({
      ...building,
      furniture: building.furniture.map((prop) =>
        prop.contractSpotId === placedId
          ? { ...prop, contractSpotId: `${placedId}${BROKEN_ID_SUFFIX}` }
          : prop,
      ),
    }));
    return { ...layout, village: { ...layout.village, buildings } };
  };
  const placedIdOf = (spot: ContractSpotDef): string =>
    spot.target.kind === 'prop' ? spot.target.placedId : spot.id;
  return [
    {
      description: 'a Skyfowl Town prop id renamed in the generated room',
      siteName: interior.site.name,
      spotId: interior.spot.id,
      apply: (layout) =>
        layout.site === interior.site ? renameProp(layout, placedIdOf(interior.spot)) : layout,
    },
    {
      description: 'a Briar Hollow furniture id renamed in the village',
      siteName: village.site.name,
      spotId: village.spot.id,
      apply: (layout) =>
        layout.site === village.site ? renameProp(layout, placedIdOf(village.spot)) : layout,
    },
    {
      description: 'a Briar Hollow building with its doorway walled up',
      siteName: doorway.site.name,
      spotId: doorway.spot.id,
      apply: (layout) => {
        if (layout.town !== 'briar_hollow' || layout.site !== doorway.site) return layout;
        const buildings = layout.village.buildings.map((building) =>
          building.id === doorway.site.buildingId ? { ...building, doorways: [] } : building,
        );
        return { ...layout, village: { ...layout.village, buildings } };
      },
    },
  ];
}

// ── Sections ─────────────────────────────────────────────────────────────

function verifySiteRoster(check: Check): void {
  const skyfowl = CONTRACT_SITES.filter((site) => site.town === 'skyfowl');
  const village = CONTRACT_SITES.filter((site) => site.town === 'briar_hollow');
  check(
    skyfowl.length === EXPECTED_SKYFOWL_SITES,
    `${EXPECTED_SKYFOWL_SITES} Skyfowl Town sites (${skyfowl.length})`,
  );
  check(
    village.length === EXPECTED_VILLAGE_SITES,
    `${EXPECTED_VILLAGE_SITES} Briar Hollow sites (${village.length})`,
  );
  const slugs = new Set(CONTRACT_SITES.map((site) => site.slug));
  check(slugs.size === CONTRACT_SITES.length, 'every site slug is unique across both towns');
  for (const site of CONTRACT_SITES) {
    const ids = new Set(site.spots.map((spot) => spot.id));
    if (ids.size !== site.spots.length) check(false, `${site.name}: spot ids are unique`);
  }
}

function verifyExclusions(check: Check): void {
  const excluded: readonly string[] = CONTRACT_EXCLUDED_TOWN_BUILDINGS;
  const named = CONTRACT_SITES.filter(
    (site) =>
      excluded.includes(site.name) ||
      (site.town === 'skyfowl' && excluded.includes(site.buildingName)),
  );
  check(named.length === 0, `no excluded building is a contract site (${excluded.join(', ')})`);
  for (const name of excluded) {
    check(skyfowlContractSite(name) === undefined, `${name}: no site is looked up for it`);
  }
  for (const seed of LAYOUT_WORLD_SEEDS) {
    const world = worldLayouts(seed);
    for (const name of excluded) {
      const entry = world.entries.find((candidate) => candidate.name === name);
      if (entry === undefined) {
        check(false, `seed ${seed}: ${name} has a building entry`);
        continue;
      }
      const carried = generateGroundFloor(entry)
        .placedInteriorProps.map((prop) => prop.id)
        .filter((id) => id.startsWith(CONTRACT_PROP_ID_PREFIX));
      check(
        carried.length === 0,
        `seed ${seed}: ${name}'s ground floor carries no contract prop id${carried.length > 0 ? ` (${carried.join(', ')})` : ''}`,
      );
    }
  }
}

function verifyTargets(check: Check, breaks: readonly LayoutBreak[]): void {
  for (const seed of LAYOUT_WORLD_SEEDS) {
    const world = worldLayouts(seed);
    for (const site of CONTRACT_SITES) {
      const built = siteLayout(site, world);
      if (typeof built === 'string') {
        check(false, built);
        continue;
      }
      const layout = breaks.reduce((current, layoutBreak) => layoutBreak.apply(current), built);
      reportSite(
        check,
        `seed ${seed} · ${site.name}: all ${site.spots.length} spots resolve once, on the right surface, apart`,
        siteTargetProblems(layout),
      );
    }
  }
}

function sameMembers(a: readonly string[], b: readonly string[]): boolean {
  return a.length === b.length && a.every((id) => b.includes(id));
}

function verifyPools(check: Check): void {
  for (const site of CONTRACT_SITES) {
    const sets = validSpotSets(site);
    const faults: string[] = [];
    sets.forEach((set, index) => {
      const spots = set.flatMap((id) => site.spots.filter((spot) => spot.id === id));
      if (spots.length !== set.length || new Set(set).size !== set.length) {
        faults.push(`set ${index} names a spot twice or outside the pool`);
      }
      if (set.length < CONTRACT_MIN_SPOTS || set.length > CONTRACT_MAX_SPOTS) {
        faults.push(`set ${index} has ${set.length} spots`);
      }
      for (const material of CONTRACT_MATERIALS) {
        const total = spots.reduce((sum, spot) => sum + spot.cost[material], 0);
        const band = CONTRACT_MATERIAL_BANDS[material];
        if (total < band.min || total > band.max)
          faults.push(`set ${index} has ${total} ${material}`);
      }
      if (sets.slice(0, index).some((earlier) => sameMembers(earlier, set))) {
        faults.push(`set ${index} repeats an earlier set`);
      }
    });
    reportSite(
      check,
      `${site.name}: ${sets.length} distinct valid contracts (at least ${CONTRACT_MIN_DISTINCT_SETS})`,
      sets.length < CONTRACT_MIN_DISTINCT_SETS ? [...faults, 'too few contracts'] : faults,
    );
  }
}

/**
 * Each deliberate break on its own, against a clean world: the check must
 * fail, and its report must name the broken building and spot.
 */
function verifyBreaksAreCaught(check: Check): void {
  const world = worldLayouts(LAYOUT_WORLD_SEEDS[0]);
  for (const layoutBreak of layoutBreaks()) {
    const site = CONTRACT_SITES.find((candidate) => candidate.name === layoutBreak.siteName);
    const built = site === undefined ? 'no such site' : siteLayout(site, world);
    if (typeof built === 'string') {
      check(false, `negative: ${layoutBreak.description} (${built})`);
      continue;
    }
    const clean = siteTargetProblems(built);
    const problems = siteTargetProblems(layoutBreak.apply(built));
    const named = problems.filter(
      (problem) =>
        problem.includes(layoutBreak.siteName) && problem.includes(`"${layoutBreak.spotId}"`),
    );
    for (const problem of named) console.log(`         caught: ${problem}`);
    check(
      clean.length === 0 && named.length > 0,
      `negative: ${layoutBreak.description} goes red naming ${layoutBreak.siteName} / "${layoutBreak.spotId}"`,
    );
  }
}

export interface TargetSectionOptions {
  /** Applies every deliberate break to the main pass, so the whole gate goes red. */
  readonly breakLayouts: boolean;
}

export function targetSections(options: TargetSectionOptions): ReadonlyArray<{
  readonly name: string;
  readonly run: (check: Check) => void;
}> {
  return [
    { name: 'Site roster', run: verifySiteRoster },
    { name: 'Excluded buildings', run: verifyExclusions },
    {
      name: 'Every target resolves in the built layouts',
      run: (check) => verifyTargets(check, options.breakLayouts ? layoutBreaks() : []),
    },
    { name: 'Every pool offers enough contracts', run: verifyPools },
    { name: 'Negative: a broken layout id goes red', run: verifyBreaksAreCaught },
  ];
}
