const SOUND_IDS_TUPLE = [
  'bg_level_1',
  'boss_music_1',
  'boss_music_2',
  'boss_music_3',
  'defense_quest_music',
  'cat_missile_fire',
  'cat_missile_impact',
  'cat_scratch',
  'cat_effect_damage_1',
  'cat_effect_damage_2',
  'cat_effect_damage_3',
  'healing_potion',
  'human_punch_1',
  'human_punch_2',
  'human_punch_3',
  'human_punch_weak',
  'human_protective_shell',
  'human_effect_damage_1',
  'human_effect_damage_2',
  'hoarder_damage_1',
  'hoarder_damage_2',
  'hoarder_damage_3',
  'hoarder_vomit',
  'juicer_throw',
  'pickup_1',
  'pickup_2',
  'goblin_1',
  'goblin_2',
  'goblin_found_you',
  'llama_fireball',
  'llama_fireball_explosion',
  'rat_squeak_1',
  'rat_squeak_2',
  'rat_squeak_3',
  'splat_1',
  'splat_2',
  'splat_3',
  'entered_safe_room',
  'player_level_up',
  'ability_level_up',
  'player_walking',
  'dynamite_explosion',
  'confusing_fog',
  'menu_change_follower',
  'menu_drop_item',
  'menu_expand_map',
  'menu_click',
  'menu_open',
  'menu_skillpoint_spent',
  'sword_attack_1',
  'ball_of_swine_rolling',
  'boss_defeated',
  'mongo_released',
  'mongo_slash',
  'skyfowl_1',
  'skyfowl_2',
  'troglodyte_tongue',
  'tuskling_grunt_1',
  'tuskling_grunt_2',
  'tuskling_grunt_3',
  'tuskling_grunt_4',
  'level_complete',
  'new_unlock',
  'objective_complete',
  'purchase_success',
  'quest_complete',
  'hammer_strike',
  'krakaren_yell',
  'krakaren_ground_slam',
  'wood_breaking_1',
  'wood_breaking_2',
  'wood_breaking_3',
  'grotesque_spider_slam_attack',
  'grotesque_spider_screech_attack',
  'grotesque_spider_spit_attack',
  'grotesque_spider_spit_landing',
  'spider_walking',
] as const;

export type SoundId = (typeof SOUND_IDS_TUPLE)[number];

/** All valid sound IDs. Use as the default argument for AudioManager.preload(). */
export const ALL_SOUND_IDS: ReadonlyArray<SoundId> = SOUND_IDS_TUPLE;

/** Maps every SoundId to its asset path relative to the document root. */
export const SOUND_MANIFEST: Record<SoundId, string> = {
  bg_level_1: './src/audio/background_music/background_music_level_1.mp3',
  boss_music_1: './src/audio/background_music/boss_music_1.mp3',
  boss_music_2: './src/audio/background_music/boss_music_2.mp3',
  boss_music_3: './src/audio/background_music/boss_music_3.mp3',
  defense_quest_music: './src/audio/background_music/defense_quest_music.mp3',
  cat_missile_fire: './src/audio/characters/cat/magic_missile_fire.mp3',
  cat_missile_impact: './src/audio/characters/cat/magic_missle_impact.mp3',
  cat_scratch: './src/audio/characters/cat/scratch.mp3',
  cat_effect_damage_1: './src/audio/characters/cat/cat_taking_effect_damage_1.mp3',
  cat_effect_damage_2: './src/audio/characters/cat/cat_taking_effect_damage_2.mp3',
  cat_effect_damage_3: './src/audio/characters/cat/cat_taking_effect_damage_3.mp3',
  healing_potion: './src/audio/characters/healing_potion.mp3',
  human_punch_1: './src/audio/characters/human/punch_1.mp3',
  human_punch_2: './src/audio/characters/human/punch_2.mp3',
  human_punch_3: './src/audio/characters/human/punch_3.mp3',
  human_punch_weak: './src/audio/characters/human/punch_weak_hit.mp3',
  human_protective_shell: './src/audio/characters/human/protective_shell_discharge.mp3',
  human_effect_damage_1: './src/audio/characters/human/human_taking_effect_damage_1.mp3',
  human_effect_damage_2: './src/audio/characters/human/human_taking_effect_damage_2.mp3',
  hoarder_damage_1: './src/audio/bosses/hoarder/hoarder_taking_damage_1.mp3',
  hoarder_damage_2: './src/audio/bosses/hoarder/hoarder_taking_damage_2.mp3',
  hoarder_damage_3: './src/audio/bosses/hoarder/hoarder_taking_damage_3.mp3',
  hoarder_vomit: './src/audio/bosses/hoarder/hoarder_vomiting.mp3',
  juicer_throw: './src/audio/bosses/juicer/juicer_throwing.mp3',
  pickup_1: './src/audio/characters/pickup_items_1.mp3',
  pickup_2: './src/audio/characters/pickup_items_2.mp3',
  goblin_1: './src/audio/enemies/goblin/goblin_1.mp3',
  goblin_2: './src/audio/enemies/goblin/goblin_2.mp3',
  goblin_found_you: './src/audio/enemies/goblin/goblin_I_found_you_speech.mp3',
  llama_fireball: './src/audio/enemies/llama/llama_fireball.mp3',
  llama_fireball_explosion: './src/audio/enemies/llama/llama_fireball_explosion.mp3',
  rat_squeak_1: './src/audio/enemies/rat/rat_squeak_1.mp3',
  rat_squeak_2: './src/audio/enemies/rat/rat_squeaks_2.mp3',
  rat_squeak_3: './src/audio/enemies/rat/rat_squeak_3.mp3',
  splat_1: './src/audio/enemies/splat_1.mp3',
  splat_2: './src/audio/enemies/splat_2.mp3',
  splat_3: './src/audio/enemies/splat_3.mp3',
  entered_safe_room: './src/audio/events/entered_safe_room.mp3',
  player_level_up: './src/audio/characters/player_level_up.mp3',
  ability_level_up: './src/audio/characters/ability_level_up.mp3',
  player_walking: './src/audio/characters/player_walking_loop_segment.mp3',
  dynamite_explosion: './src/audio/effects/dynamite_explosion.mp3',
  confusing_fog: './src/audio/effects/scroll_of_confusing_fog.mp3',
  menu_change_follower: './src/audio/menu/change_follower_behavior.mp3',
  menu_drop_item: './src/audio/menu/drop_item_from_inventory.mp3',
  menu_expand_map: './src/audio/menu/expand_map.mp3',
  menu_click: './src/audio/menu/menu_click.mp3',
  menu_open: './src/audio/menu/open_menu.mp3',
  menu_skillpoint_spent: './src/audio/menu/skillpoint_spent.mp3',
  sword_attack_1: './src/audio/sword_attack_1.mp3',
  ball_of_swine_rolling: './src/audio/bosses/ball_of_swine/ball_of_swine_rolling.mp3',
  boss_defeated: './src/audio/bosses/boss_defeated.mp3',
  mongo_released: './src/audio/characters/mongo/mongo_released.mp3',
  mongo_slash: './src/audio/characters/mongo/mongo_slash.mp3',
  skyfowl_1: './src/audio/enemies/sky_fowl/skyfowl_1.mp3',
  skyfowl_2: './src/audio/enemies/sky_fowl/skyfowl_2.mp3',
  troglodyte_tongue: './src/audio/enemies/troglodyte/troglodyte_tongue.mp3',
  tuskling_grunt_1: './src/audio/enemies/tuskling/tuskling_grunt_1.mp3',
  tuskling_grunt_2: './src/audio/enemies/tuskling/tuskling_grunt_2.mp3',
  tuskling_grunt_3: './src/audio/enemies/tuskling/tuskling_grunt_3.mp3',
  tuskling_grunt_4: './src/audio/enemies/tuskling/tuskling_grunt_4.mp3',
  level_complete: './src/audio/events/level_complete.mp3',
  new_unlock: './src/audio/events/new_unlock.mp3',
  objective_complete: './src/audio/events/objective_complete.mp3',
  purchase_success: './src/audio/events/purchase_success.mp3',
  quest_complete: './src/audio/events/quest_complete.mp3',
  hammer_strike: './src/audio/characters/human/hammer_strike.mp3',
  krakaren_yell: './src/audio/bosses/krakaren/krakaren_yell.mp3',
  krakaren_ground_slam: './src/audio/bosses/krakaren/krakaren_ground_slam.mp3',
  wood_breaking_1: './src/audio/effects/wood_breaking_1.mp3',
  wood_breaking_2: './src/audio/effects/wood_breaking_2.mp3',
  wood_breaking_3: './src/audio/effects/wood_breaking_3.mp3',
  grotesque_spider_slam_attack:
    './src/audio/enemies/grotesque_spider/grotesque_spider_slam_attack.mp3',
  grotesque_spider_screech_attack:
    './src/audio/enemies/grotesque_spider/grotesque_spider_screech_attack.mp3',
  grotesque_spider_spit_attack:
    './src/audio/enemies/grotesque_spider/grotesque_spider_spit_attack.mp3',
  grotesque_spider_spit_landing:
    './src/audio/enemies/grotesque_spider/grotesque_spider_spit_landing.mp3',
  spider_walking: './src/audio/enemies/grotesque_spider/spider_walking.mp3',
};
