const SOUND_IDS_TUPLE = [
  'bg_level_1',
  'cat_missile_fire',
  'cat_missile_impact',
  'cat_scratch',
  'healing_potion',
  'human_punch_1',
  'human_punch_2',
  'human_punch_3',
  'human_punch_weak',
  'human_protective_shell',
  'pickup_1',
  'pickup_2',
  'goblin_1',
  'goblin_2',
  'goblin_found_you',
  'llama_fireball',
  'llama_fireball_explosion',
  'rat_squeak_1',
  'rat_squeak_2',
  'rat_squeak_3',
  'splat_1',
  'splat_2',
  'splat_3',
  'entered_safe_room',
  'menu_change_follower',
  'menu_drop_item',
  'menu_expand_map',
  'menu_click',
  'menu_open',
  'menu_skillpoint_spent',
  'sword_attack_1',
] as const;

export type SoundId = (typeof SOUND_IDS_TUPLE)[number];

/** All valid sound IDs. Use as the default argument for AudioManager.preload(). */
export const ALL_SOUND_IDS: ReadonlyArray<SoundId> = SOUND_IDS_TUPLE;

/** Maps every SoundId to its asset path relative to the document root. */
export const SOUND_MANIFEST: Record<SoundId, string> = {
  bg_level_1: './src/audio/background_music/background_music_level_1.mp3',
  cat_missile_fire: './src/audio/characters/cat/magic_missile_fire.mp3',
  cat_missile_impact: './src/audio/characters/cat/magic_missle_impact.mp3',
  cat_scratch: './src/audio/characters/cat/scratch.mp3',
  healing_potion: './src/audio/characters/healing_potion.mp3',
  human_punch_1: './src/audio/characters/human/punch_1.mp3',
  human_punch_2: './src/audio/characters/human/punch_2.mp3',
  human_punch_3: './src/audio/characters/human/punch_3.mp3',
  human_punch_weak: './src/audio/characters/human/punch_weak_hit.mp3',
  human_protective_shell: './src/audio/characters/human/protective_shell_discharge.mp3',
  pickup_1: './src/audio/characters/pickup_items_1.mp3',
  pickup_2: './src/audio/characters/pickup_items_2.mp3',
  goblin_1: './src/audio/enemies/goblin/goblin_1.mp3',
  goblin_2: './src/audio/enemies/goblin/goblin_2.mp3',
  goblin_found_you: './src/audio/enemies/goblin/goblin_I_found_you_speech.mp3',
  llama_fireball: './src/audio/enemies/llama/llama_fireball.mp3',
  llama_fireball_explosion: './src/audio/enemies/llama/llama_fireball_explosion.mp3',
  rat_squeak_1: './src/audio/enemies/rat/rat_squeak_1.mp3',
  rat_squeak_2: './src/audio/enemies/rat/rat_squeaks_2.mp3',
  rat_squeak_3: './src/audio/enemies/rat/rat_squeak_3.mp3',
  splat_1: './src/audio/enemies/splat_1.mp3',
  splat_2: './src/audio/enemies/splat_2.mp3',
  splat_3: './src/audio/enemies/splat_3.mp3',
  entered_safe_room: './src/audio/events/entered_safe_room.mp3',
  menu_change_follower: './src/audio/menu/change_follower_behavior.mp3',
  menu_drop_item: './src/audio/menu/drop_item_from_inventory.mp3',
  menu_expand_map: './src/audio/menu/expand_map.mp3',
  menu_click: './src/audio/menu/menu_click.mp3',
  menu_open: './src/audio/menu/open_menu.mp3',
  menu_skillpoint_spent: './src/audio/menu/skillpoint_spent.mp3',
  sword_attack_1: './src/audio/sword_attack_1.mp3',
};
