const SOUND_IDS_TUPLE = [
  'ability_level_up',
  'achievement_awarded',
  'achievement_unlocked',
  'ambient_bar_crowd',
  'ambient_city_crowd_chatting',
  'ambient_fire_crackling',
  'ambient_fountain',
  'ambient_magic_shop',
  'ambient_pouring_a_drink',
  'ambient_river_flowing',
  'ambient_town_square_crowd',
  'ball_of_swine_rolling',
  'bear_big_attack',
  'bear_growl_1',
  'bg_level_1',
  'bg_level_2',
  'big_tower_music',
  'boss_defeated',
  'boss_music_1',
  'boss_music_2',
  'boss_music_3',
  'bopca_cooking',
  'bopca_dish_set_down',
  'bopca_eating',
  'bopca_grunt',
  'bopca_happy_grunt',
  'building_default_music_1',
  'casino_blackjack_check',
  'casino_chips_bet_big',
  'casino_chips_bet_small',
  'casino_chips_stack',
  'casino_deal_card',
  'casino_deal_four_cards',
  'casino_shuffle_1',
  'casino_shuffle_2',
  'cat_effect_damage_1',
  'cat_effect_damage_2',
  'cat_effect_damage_3',
  'cat_knocked_out',
  'cat_missile_fire',
  'cat_missile_impact',
  'cat_revived',
  'cat_splash',
  'cat_scratch',
  'chest_locked',
  'chest_unlocked_in_treasure_room',
  'circus_battle',
  'circus_lemur_attack',
  'circus_lemur_sound',
  'circus_theme',
  'clown_burp',
  'clown_come_here',
  'clown_horn',
  'clown_laughing_1',
  'clown_laughing_2',
  'coin_pouch',
  'confusing_fog',
  'cooldown_crisp',
  'death_sequence',
  'defense_quest_music',
  'desperado_club_1',
  'desperado_club_2',
  'desperado_club_3',
  'desperado_club_4',
  'dynamite_explosion',
  'entered_safe_room',
  'error_taking_action',
  'error',
  'flesh_being_sliced',
  'forest_path',
  'gate_opening',
  'goblin_1',
  'goblin_2',
  'goblin_found_you',
  'grimaldi_plant_moving_1',
  'grimaldi_plant_moving_2',
  'grimaldi_plant_moving_3',
  'grimaldi_vine_taking_damage',
  'grotesque_spider_screech_attack',
  'grotesque_spider_slam_attack',
  'grotesque_spider_spit_attack',
  'grotesque_spider_spit_landing',
  'hammer_strike',
  'healing_potion',
  'hoarder_damage_1',
  'hoarder_damage_2',
  'hoarder_damage_3',
  'hoarder_vomit',
  'human_effect_damage_1',
  'human_effect_damage_2',
  'human_knocked_out',
  'human_protective_shell',
  'human_punch_1',
  'human_punch_2',
  'human_punch_3',
  'human_punch_weak',
  'human_revived',
  'human_smush',
  'human_splash',
  'jugg_juice',
  'juicer_throw',
  'keyboard_hero_music_track_1',
  'krakaren_ground_slam',
  'krakaren_yell',
  'krasue_attack',
  'level_begins',
  'level_complete',
  'life_machine_powering_on',
  'llama_fireball_explosion',
  'llama_fireball',
  'menu_change_follower',
  'menu_click',
  'menu_drop_item',
  'menu_expand_map',
  'menu_open',
  'menu_skillpoint_spent',
  'mob_splash',
  'mongo_released',
  'mongo_slash',
  'new_unlock',
  'objective_complete',
  'opening_reward_box',
  'opening_treasure_chest',
  'pickup_1',
  'pickup_2',
  'player_level_up',
  'player_wading',
  'player_walking',
  'potion_drink',
  'powering_off',
  'purchase_success',
  'quest_complete',
  'rat_squeak_1',
  'rat_squeak_2',
  'rat_squeak_3',
  'reviving_tone',
  'rumble',
  'scientist_exclaiming_about_an_escape',
  'scientist_explaining_request',
  'skyfowl_1',
  'skyfowl_2',
  'speed_fizz',
  'spider_walking',
  'splat_1',
  'splat_2',
  'splat_3',
  'stat_boost',
  'sword_attack_1',
  'tavern_music_1',
  'tavern_music_2',
  'tech_machinery_running',
  'town_music_1',
  'town_music_2',
  'treasure_chest_reward',
  'troglodyte_tongue',
  'tuskling_grunt_1',
  'tuskling_grunt_2',
  'tuskling_grunt_3',
  'tuskling_grunt_4',
  'tutorial_island',
  'typing_click',
  'wood_breaking_1',
  'wood_breaking_2',
  'wood_breaking_3',
  'wood_smashing_1',
  'wood_smashing_2',
] as const;

export type SoundId = (typeof SOUND_IDS_TUPLE)[number];

/** All valid sound IDs. Use as the default argument for AudioManager.preload(). */
export const ALL_SOUND_IDS: ReadonlyArray<SoundId> = SOUND_IDS_TUPLE;

/** Maps every SoundId to its asset path relative to the document root. */
export const SOUND_MANIFEST: Record<SoundId, string> = {
  ability_level_up: './src/audio/characters/ability_level_up.mp3',
  achievement_awarded: './src/audio/events/achievement_awarded.mp3',
  achievement_unlocked: './src/audio/events/achievement_unlocked.mp3',
  ambient_bar_crowd: './src/audio/ambient/bar_crowd.mp3',
  ambient_city_crowd_chatting: './src/audio/ambient/city_crowd_chatting.mp3',
  ambient_fire_crackling: './src/audio/ambient/fire_crackling.mp3',
  ambient_fountain: './src/audio/ambient/fountain.mp3',
  ambient_magic_shop: './src/audio/ambient/magic_shop.mp3',
  ambient_pouring_a_drink: './src/audio/ambient/pouring_a_drink.mp3',
  ambient_river_flowing: './src/audio/ambient/river_flowing.mp3',
  ambient_town_square_crowd: './src/audio/ambient/town_square_crowd.mp3',
  ball_of_swine_rolling: './src/audio/bosses/ball_of_swine/ball_of_swine_rolling.mp3',
  bear_big_attack: './src/audio/enemies/bear/bear_big_attack.mp3',
  bear_growl_1: './src/audio/enemies/bear/bear_growl_1.mp3',
  bg_level_1: './src/audio/background_music/background_music_level_1.mp3',
  bg_level_2: './src/audio/background_music/level_background_music_2.mp3',
  big_tower_music: './src/audio/background_music/big_tower_music.mp3',
  boss_defeated: './src/audio/bosses/boss_defeated.mp3',
  boss_music_1: './src/audio/background_music/boss_music_1.mp3',
  boss_music_2: './src/audio/background_music/boss_music_2.mp3',
  boss_music_3: './src/audio/background_music/boss_music_3.mp3',
  bopca_cooking: './src/audio/characters/bopca/cooking.mp3',
  bopca_dish_set_down: './src/audio/characters/bopca/plate_setting_down.mp3',
  bopca_eating: './src/audio/characters/bopca/eating.mp3',
  bopca_grunt: './src/audio/characters/bopca/grunt.mp3',
  bopca_happy_grunt: './src/audio/characters/bopca/happy_grunt.mp3',
  building_default_music_1: './src/audio/background_music/building_default_music_1.mp3',
  casino_blackjack_check: './src/audio/casino/blackjack_check.mp3',
  casino_chips_bet_big: './src/audio/casino/chips_bet_big.mp3',
  casino_chips_bet_small: './src/audio/casino/chips_bet_small.mp3',
  casino_chips_stack: './src/audio/casino/chips_stack.mp3',
  casino_deal_card: './src/audio/casino/deal_card.mp3',
  casino_deal_four_cards: './src/audio/casino/deal_four_cards.mp3',
  casino_shuffle_1: './src/audio/casino/shuffle_1.mp3',
  casino_shuffle_2: './src/audio/casino/shuffle_2.mp3',
  cat_effect_damage_1: './src/audio/characters/cat/cat_taking_effect_damage_1.mp3',
  cat_effect_damage_2: './src/audio/characters/cat/cat_taking_effect_damage_2.mp3',
  cat_effect_damage_3: './src/audio/characters/cat/cat_taking_effect_damage_3.mp3',
  cat_knocked_out: './src/audio/characters/cat/cat_knocked_out.mp3',
  cat_missile_fire: './src/audio/characters/cat/magic_missile_fire.mp3',
  cat_missile_impact: './src/audio/characters/cat/magic_missle_impact.mp3',
  cat_revived: './src/audio/characters/cat/cat_revived.mp3',
  cat_scratch: './src/audio/characters/cat/scratch.mp3',
  cat_splash: './src/audio/characters/cat/splash.mp3',
  chest_locked: './src/audio/events/chest_locked.mp3',
  chest_unlocked_in_treasure_room: './src/audio/events/chest_unlocked_in_treasure_room.mp3',
  circus_battle: './src/audio/background_music/circus_battle.mp3',
  circus_lemur_attack: './src/audio/enemies/circus_lemur/lemur_attack.mp3',
  circus_lemur_sound: './src/audio/enemies/circus_lemur/lemur_sound.mp3',
  circus_theme: './src/audio/background_music/circus_theme.mp3',
  clown_burp: './src/audio/enemies/clown/clown_burp.mp3',
  clown_come_here: './src/audio/enemies/clown/clown_saying_come_here.mp3',
  clown_horn: './src/audio/enemies/clown/clown_horn.mp3',
  clown_laughing_1: './src/audio/enemies/clown/clowns_laughing_1.mp3',
  clown_laughing_2: './src/audio/enemies/clown/clowns_laughing_2.mp3',
  coin_pouch: './src/audio/effects/coin_pouch.mp3',
  confusing_fog: './src/audio/effects/scroll_of_confusing_fog.mp3',
  cooldown_crisp: './src/audio/effects/cooldown_crisp_effect.mp3',
  death_sequence: './src/audio/events/death_sequence.mp3',
  defense_quest_music: './src/audio/background_music/defense_quest_music.mp3',
  desperado_club_1: './src/audio/background_music/desperado_club_1.mp3',
  desperado_club_2: './src/audio/background_music/desperado_club_2.mp3',
  desperado_club_3: './src/audio/background_music/desperado_club_3.mp3',
  desperado_club_4: './src/audio/background_music/desperado_club_4.mp3',
  dynamite_explosion: './src/audio/effects/dynamite_explosion.mp3',
  entered_safe_room: './src/audio/events/entered_safe_room.mp3',
  error_taking_action: './src/audio/events/error_taking_action.mp3',
  error: './src/audio/events/error.mp3',
  flesh_being_sliced: './src/audio/flesh_being_sliced.mp3',
  forest_path: './src/audio/background_music/forest_path.mp3',
  gate_opening: './src/audio/effects/gate_opening.mp3',
  goblin_1: './src/audio/enemies/goblin/goblin_1.mp3',
  goblin_2: './src/audio/enemies/goblin/goblin_2.mp3',
  goblin_found_you: './src/audio/enemies/goblin/goblin_I_found_you_speech.mp3',
  grimaldi_plant_moving_1: './src/audio/bosses/grimaldi/plant_moving_1.mp3',
  grimaldi_plant_moving_2: './src/audio/bosses/grimaldi/plant_moving_2.mp3',
  grimaldi_plant_moving_3: './src/audio/bosses/grimaldi/plant_moving_3.mp3',
  grimaldi_vine_taking_damage: './src/audio/bosses/grimaldi/vine_taking_damage.mp3',
  grotesque_spider_screech_attack:
    './src/audio/bosses/grotesque_spider/grotesque_spider_screech_attack.mp3',
  grotesque_spider_slam_attack:
    './src/audio/bosses/grotesque_spider/grotesque_spider_slam_attack.mp3',
  grotesque_spider_spit_attack:
    './src/audio/bosses/grotesque_spider/grotesque_spider_spit_attack.mp3',
  grotesque_spider_spit_landing:
    './src/audio/bosses/grotesque_spider/grotesque_spider_spit_landing.mp3',
  hammer_strike: './src/audio/characters/human/hammer_strike.mp3',
  healing_potion: './src/audio/characters/healing_potion.mp3',
  hoarder_damage_1: './src/audio/bosses/hoarder/hoarder_taking_damage_1.mp3',
  hoarder_damage_2: './src/audio/bosses/hoarder/hoarder_taking_damage_2.mp3',
  hoarder_damage_3: './src/audio/bosses/hoarder/hoarder_taking_damage_3.mp3',
  hoarder_vomit: './src/audio/bosses/hoarder/hoarder_vomiting.mp3',
  human_effect_damage_1: './src/audio/characters/human/human_taking_effect_damage_1.mp3',
  human_effect_damage_2: './src/audio/characters/human/human_taking_effect_damage_2.mp3',
  human_knocked_out: './src/audio/characters/human/human_knocked_out.mp3',
  human_protective_shell: './src/audio/characters/human/protective_shell_discharge.mp3',
  human_punch_1: './src/audio/characters/human/punch_1.mp3',
  human_punch_2: './src/audio/characters/human/punch_2.mp3',
  human_punch_3: './src/audio/characters/human/punch_3.mp3',
  human_punch_weak: './src/audio/characters/human/punch_weak_hit.mp3',
  human_revived: './src/audio/characters/human/human_revived.mp3',
  human_smush: './src/audio/characters/human/smush.mp3',
  human_splash: './src/audio/characters/human/splash.mp3',
  jugg_juice: './src/audio/effects/jugg_juice_effect.mp3',
  juicer_throw: './src/audio/bosses/juicer/juicer_throwing.mp3',
  keyboard_hero_music_track_1:
    './src/audio/bosses/grotesque_spider/keyboard_hero_music_track_1.mp3',
  krakaren_ground_slam: './src/audio/bosses/krakaren/krakaren_ground_slam.mp3',
  krakaren_yell: './src/audio/bosses/krakaren/krakaren_yell.mp3',
  krasue_attack: './src/audio/enemies/krasue/krasue_attack.mp3',
  level_begins: './src/audio/events/level_begins.mp3',
  level_complete: './src/audio/events/level_complete.mp3',
  life_machine_powering_on: './src/audio/bosses/grotesque_spider/life_machine_powering_on.mp3',
  llama_fireball_explosion: './src/audio/enemies/llama/llama_fireball_explosion.mp3',
  llama_fireball: './src/audio/enemies/llama/llama_fireball.mp3',
  menu_change_follower: './src/audio/menu/change_follower_behavior.mp3',
  menu_click: './src/audio/menu/menu_click.mp3',
  menu_drop_item: './src/audio/menu/drop_item_from_inventory.mp3',
  menu_expand_map: './src/audio/menu/expand_map.mp3',
  menu_open: './src/audio/menu/open_menu.mp3',
  menu_skillpoint_spent: './src/audio/menu/skillpoint_spent.mp3',
  mob_splash: './src/audio/enemies/mob_splash.mp3',
  mongo_released: './src/audio/characters/mongo/mongo_released.mp3',
  mongo_slash: './src/audio/characters/mongo/mongo_slash.mp3',
  new_unlock: './src/audio/events/new_unlock.mp3',
  objective_complete: './src/audio/events/objective_complete.mp3',
  opening_reward_box: './src/audio/events/opening_reward_box.mp3',
  opening_treasure_chest: './src/audio/events/opening-treasure-chest.mp3',
  pickup_1: './src/audio/characters/pickup_items_1.mp3',
  pickup_2: './src/audio/characters/pickup_items_2.mp3',
  player_level_up: './src/audio/characters/player_level_up.mp3',
  player_wading: './src/audio/characters/player_wading_loop.mp3',
  player_walking: './src/audio/characters/player_walking_loop_segment.mp3',
  potion_drink: './src/audio/effects/potion_drink.mp3',
  powering_off: './src/audio/events/power_off.mp3',
  purchase_success: './src/audio/events/purchase_success.mp3',
  quest_complete: './src/audio/events/quest_complete.mp3',
  rat_squeak_1: './src/audio/enemies/rat/rat_squeak_1.mp3',
  rat_squeak_2: './src/audio/enemies/rat/rat_squeaks_2.mp3',
  rat_squeak_3: './src/audio/enemies/rat/rat_squeak_3.mp3',
  reviving_tone: './src/audio/characters/reviving_tone.mp3',
  rumble: './src/audio/effects/rumble.mp3',
  scientist_exclaiming_about_an_escape:
    './src/audio/bosses/grotesque_spider/scientist_exclaiming_about_an_escape.mp3',
  scientist_explaining_request:
    './src/audio/bosses/grotesque_spider/scientist_explaining_request.mp3',
  skyfowl_1: './src/audio/enemies/sky_fowl/skyfowl_1.mp3',
  skyfowl_2: './src/audio/enemies/sky_fowl/skyfowl_2.mp3',
  speed_fizz: './src/audio/effects/speed_fizz_effect.mp3',
  spider_walking: './src/audio/bosses/grotesque_spider/spider_walking.mp3',
  splat_1: './src/audio/enemies/splat_1.mp3',
  splat_2: './src/audio/enemies/splat_2.mp3',
  splat_3: './src/audio/enemies/splat_3.mp3',
  stat_boost: './src/audio/effects/stat_boost_effect.mp3',
  sword_attack_1: './src/audio/sword_attack_1.mp3',
  tavern_music_1: './src/audio/background_music/tavern_music_1.mp3',
  tavern_music_2: './src/audio/background_music/tavern_music_2.mp3',
  tech_machinery_running: './src/audio/bosses/grotesque_spider/tech_machinery_running.mp3',
  town_music_1: './src/audio/background_music/town_music_1.mp3',
  town_music_2: './src/audio/background_music/town_music_2.mp3',
  treasure_chest_reward: './src/audio/events/treasure-chest-reward.mp3',
  troglodyte_tongue: './src/audio/enemies/troglodyte/troglodyte_tongue.mp3',
  tuskling_grunt_1: './src/audio/enemies/tuskling/tuskling_grunt_1.mp3',
  tuskling_grunt_2: './src/audio/enemies/tuskling/tuskling_grunt_2.mp3',
  tuskling_grunt_3: './src/audio/enemies/tuskling/tuskling_grunt_3.mp3',
  tuskling_grunt_4: './src/audio/enemies/tuskling/tuskling_grunt_4.mp3',
  tutorial_island: './src/audio/background_music/tutorial_island.mp3',
  typing_click: './src/audio/effects/typing_click.mp3',
  wood_breaking_1: './src/audio/effects/wood_breaking_1.mp3',
  wood_breaking_2: './src/audio/effects/wood_breaking_2.mp3',
  wood_breaking_3: './src/audio/effects/wood_breaking_3.mp3',
  wood_smashing_1: './src/audio/effects/wood_smashing_1.mp3',
  wood_smashing_2: './src/audio/effects/wood_smashing_2.mp3',
};

/** The Desperado Club's rotating soundtrack — a shuffled, looping playlist entered on club arrival. */
export const CLUB_MUSIC_TRACKS: ReadonlyArray<SoundId> = [
  'desperado_club_1',
  'desperado_club_2',
  'desperado_club_3',
  'desperado_club_4',
];

/** The town's rotating soundtrack — reshuffled each time the player walks back into the safe zone. */
export const TOWN_MUSIC_TRACKS: ReadonlyArray<SoundId> = ['town_music_1', 'town_music_2'];

/** The town taverns' rotating soundtrack — shuffled and looping while the player is inside. */
export const TAVERN_MUSIC_TRACKS: ReadonlyArray<SoundId> = ['tavern_music_1', 'tavern_music_2'];

/** The Town Center Tower's own theme, playing on every floor until the Quill confrontation takes over. */
export const TOWER_MUSIC_TRACKS: ReadonlyArray<SoundId> = ['big_tower_music'];

/** Fallback interior music for buildings with no soundtrack of their own. */
export const DEFAULT_BUILDING_MUSIC_TRACKS: ReadonlyArray<SoundId> = ['building_default_music_1'];

/**
 * Every `background_music/` and `ambient/` id. These are long, streamed via
 * `MediaElementAudioSourceNode` rather than decoded into a resident
 * `AudioBuffer` — decoding them all as Float32 PCM is ~828 MB for audio that
 * is played one or two at a time.
 *
 * `AudioManager.preload` excludes these ids by default and `startMusicTrack`/
 * `startAmbientLoop` route them through the streaming path instead of
 * `buffers`.
 */
export const STREAMING_SOUND_IDS: ReadonlySet<SoundId> = new Set<SoundId>([
  // background_music/
  'bg_level_1',
  'bg_level_2',
  'big_tower_music',
  'boss_music_1',
  'boss_music_2',
  'boss_music_3',
  'building_default_music_1',
  'circus_battle',
  'circus_theme',
  'defense_quest_music',
  'desperado_club_1',
  'desperado_club_2',
  'desperado_club_3',
  'desperado_club_4',
  'forest_path',
  'tavern_music_1',
  'tavern_music_2',
  'town_music_1',
  'town_music_2',
  'tutorial_island',
  // ambient/
  'ambient_bar_crowd',
  'ambient_city_crowd_chatting',
  'ambient_fire_crackling',
  'ambient_fountain',
  'ambient_magic_shop',
  'ambient_pouring_a_drink',
  'ambient_river_flowing',
  'ambient_town_square_crowd',
]);

/** Every sound id not covered by `STREAMING_SOUND_IDS` — the default `preload()` set. */
export const NON_STREAMING_SOUND_IDS: ReadonlyArray<SoundId> = ALL_SOUND_IDS.filter(
  (id) => !STREAMING_SOUND_IDS.has(id),
);
