/**
 * Generates sw.js with a hardcoded PRECACHE_ASSETS list containing every
 * image and audio file the game actually loads, so the service worker can
 * pre-cache the full game on install for offline play.
 *
 * Called automatically from build.js after esbuild finishes.
 * Also runnable directly: node scripts/generate-sw.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { ROOT, collectShippedAssets, reportAssetSelection } from './shipped-assets.js';

export function generateServiceWorker() {
  const selection = collectShippedAssets();
  reportAssetSelection(selection);
  const { images: imageFiles, audio: audioFiles } = selection;

  const CACHE_VERSION = `v${Date.now()}`;

  // sw.js is deliberately absent — a service worker never pre-caches itself.
  const CORE_FILES = ['./index.html', './main.css', './manifest.json', './dist/bundle.js'];

  const ALL_ASSETS = [
    ...CORE_FILES,
    ...imageFiles.map((f) => `./${f}`),
    ...audioFiles.map((f) => `./${f}`),
  ];

  const swContent = `// Generated by scripts/generate-sw.js — do not edit manually.
// Re-run \`npm run build\` to regenerate after adding/removing assets.
const CACHE_NAME = '${CACHE_VERSION}';
const PRECACHE_ASSETS = ${JSON.stringify(ALL_ASSETS, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_ASSETS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  const isHtml = event.request.headers.get('accept')?.includes('text/html') ?? false;

  if (isHtml) {
    // Network-first for HTML so that game updates reach the user.
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
          return response;
        })
        .catch(() => caches.match(event.request)),
    );
    return;
  }

  // Cache-first for all other assets (JS, images, audio, CSS).
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached !== undefined) return cached;
      return fetch(event.request).then((response) => {
        if (response.ok) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
        }
        return response;
      });
    }),
  );
});
`;

  fs.writeFileSync(path.join(ROOT, 'sw.js'), swContent);
  console.log(
    `Generated sw.js — ${ALL_ASSETS.length} assets pre-cached (${imageFiles.length} images, ${audioFiles.length} audio, ${CORE_FILES.length} core) — cache: ${CACHE_VERSION}`,
  );
}

// Allow running directly: node scripts/generate-sw.js
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateServiceWorker();
}
