/**
 * Generates sw.js with a hardcoded PRECACHE_ASSETS list containing every
 * image and audio file the game actually loads, so the service worker can
 * pre-cache the full game on install for offline play.
 *
 * The worker never answers from its cache while the network is reachable; see
 * the fetch handler below. sw.js is a build output, not a tracked file.
 *
 * Called automatically from build.js after esbuild finishes.
 * Also runnable directly: node scripts/generate-sw.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { ROOT, collectShippedAssets, reportAssetSelection } from './shipped-assets.js';

export function generateServiceWorker() {
  const selection = collectShippedAssets();
  reportAssetSelection(selection);
  const { images: imageFiles, audio: audioFiles } = selection;

  const CACHE_VERSION = `v${Date.now()}`;

  // sw.js is deliberately absent — a service worker never pre-caches itself.
  const CORE_FILES = ['./index.html', './main.css', './manifest.json', './dist/bundle.js'];

  const ALL_ASSETS = [
    ...CORE_FILES,
    ...imageFiles.map((f) => `./${f}`),
    ...audioFiles.map((f) => `./${f}`),
  ];

  const swContent = `// Generated by scripts/generate-sw.js — do not edit manually.
// Re-run \`npm run build\` to regenerate after adding/removing assets.
const CACHE_NAME = '${CACHE_VERSION}';
const PRECACHE_ASSETS = ${JSON.stringify(ALL_ASSETS, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) =>
        cache.addAll(PRECACHE_ASSETS.map((asset) => new Request(asset, { cache: 'no-cache' }))),
      )
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

/**
 * Network-first for everything: a player online always gets the build that is
 * deployed right now. The cache exists only so an installed app still starts
 * with no connection at all.
 *
 * \`cache: 'no-cache'\` makes the browser revalidate with the server even when
 * its HTTP cache holds a copy it still considers fresh (GitHub Pages serves
 * everything with a ten-minute max-age). Navigations cannot be re-issued with a
 * different cache mode, but HTML is always served no-cache anyway.
 *
 * An offline navigation falls back to the precached index.html, because the
 * very first visit — the one that installed this worker — was not routed
 * through it, so the start URL itself was never cached.
 */
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  const networkRequest =
    event.request.mode === 'navigate'
      ? event.request
      : new Request(event.request, { cache: 'no-cache' });

  event.respondWith(
    fetch(networkRequest)
      .then((response) => {
        // Audio elements issue Range requests; a 206 is a slice, and
        // Cache.put rejects partial responses outright.
        const isCompleteResponse = response.status === 200;
        if (isCompleteResponse) {
          const clone = response.clone();
          event.waitUntil(
            caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone)),
          );
        }
        return response;
      })
      .catch(async () => {
        const cached = await caches.match(event.request);
        if (cached !== undefined) return cached;
        if (event.request.mode === 'navigate') {
          const shell = await caches.match('./index.html');
          if (shell !== undefined) return shell;
        }
        return Response.error();
      }),
  );
});
`;

  fs.writeFileSync(path.join(ROOT, 'sw.js'), swContent);
  console.log(
    `Generated sw.js — ${ALL_ASSETS.length} assets pre-cached (${imageFiles.length} images, ${audioFiles.length} audio, ${CORE_FILES.length} core) — cache: ${CACHE_VERSION}`,
  );
}

// Allow running directly: node scripts/generate-sw.js
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateServiceWorker();
}
