/**
 * Which set of materials the dungeon's generic floors and walls are drawn in.
 *
 * Floors 1 and 2 are generated by the same `DungeonGenerator` and carry the same
 * five tile types — `wall` plus the four generic floors `ZONE_FLOORS` assigns —
 * so the only thing that can distinguish them visually is the palette those
 * types are resolved through. A theme is that palette, plus the material a wall
 * is drawn in.
 *
 * ## Why the active theme is module state
 *
 * Nothing between `GameMap.renderCanvas` and the tile painters carries any level
 * identity: `TileChunkCache` is constructed from a structure grid and a tile
 * size, `drawTile` dispatches on a tile type, and `drawTerrainTile` is reached
 * from ten call sites in `decorationTiles.ts` and `interiorTiles.ts` that draw
 * the floor underneath a prop. Threading a palette to all of them would change
 * fourteen signatures to pass a value that is constant for the entire lifetime
 * of a map.
 *
 * So it is set once, on the one event that can change it — entering a floor —
 * and read by the painters, in the same way `getSpriteDef` is read. Exactly one
 * map is live at a time, and changing floor builds a new `GameMap` and therefore
 * a new chunk cache, so no baked chunk can outlive the theme it was baked under.
 *
 * A town building interior is a separate map with tile types of its own —
 * `INTERIOR_BOARD_FLOOR`, `INTERIOR_STONE_FLOOR`, `INTERIOR_WALL` and
 * `INTERIOR_COUNTER`, drawn through `TOWN_INTERIOR_GROUND`. It did not use to
 * be: a shop and a house were floored in `FloorTypeValue.wood`, the tower in
 * `carpet`, and every interior wall and counter run in `wall`, so an interior
 * resolved through whichever dungeon theme happened to be active and a
 * townhouse's floorboards changed with the last cellar the player walked
 * through. That is what those four types were added to end.
 */

import type { GroundPalette } from '../ground/GroundPalette';
import { FLOOR1_GROUND, FLOOR1_WALL_MATERIAL } from './floor1Materials';
import { FLOOR2_GROUND, FLOOR2_WALL_MATERIAL } from './floor2Materials';

export interface DungeonFloorTheme {
  /** The palette the four generic dungeon floor types resolve through. */
  readonly ground: GroundPalette;
  /**
   * The material a `FloorTypeValue.wall` tile is drawn in.
   *
   * Held here rather than reached through `materialForTileType` because a wall
   * must not be a *fringe* material: the corner masks would blend masonry into
   * the floor in front of it as though a wall were another kind of ground.
   */
  readonly wallMaterial: string;
}

export type DungeonFloorThemeId = 'cellars' | 'service_level';

const THEMES: Readonly<Record<DungeonFloorThemeId, DungeonFloorTheme>> = {
  cellars: { ground: FLOOR1_GROUND, wallMaterial: FLOOR1_WALL_MATERIAL },
  service_level: { ground: FLOOR2_GROUND, wallMaterial: FLOOR2_WALL_MATERIAL },
};

/**
 * What a level with no `groundTheme` of its own is drawn in.
 *
 * Nothing reaches it today — every `LevelDef` names a theme, and a town building
 * interior has tile types of its own — so this is the answer to "a floor was
 * added and nobody said what it is made of", not a live code path. Floor 1's,
 * because a floor that forgot to declare itself is far more likely to be an
 * early one.
 *
 * It is still applied *unconditionally* on every level entry rather than only
 * when a level names a theme. That is what makes the active theme a property of
 * the level being entered instead of a leftover from the last one, and it is
 * cheap insurance: the failure it prevents is silent and only shows up as art
 * from the wrong floor.
 */
export const DEFAULT_DUNGEON_FLOOR_THEME: DungeonFloorThemeId = 'cellars';

let activeTheme: DungeonFloorTheme = THEMES[DEFAULT_DUNGEON_FLOOR_THEME];

/** Sets the materials every dungeon floor and wall is drawn in from now on. */
export function setDungeonFloorTheme(id: DungeonFloorThemeId): void {
  activeTheme = THEMES[id];
}

/** The materials dungeon floors and walls are currently drawn in. */
export function dungeonFloorTheme(): DungeonFloorTheme {
  return activeTheme;
}
